# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone X",
  "iPad Pro (9.7-inch)",
])

# languages([
#   "en-US",
#   "de-DE",
#   "it-IT",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
# ])

# Choose which project/workspace to use
workspace("./ios/saywhat.xcworkspace")

# The name of the scheme which contains the UI Tests
scheme("saywhat")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# should clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# should stop after first error
stop_after_first_error(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
