fastlane_version '2.134.0'

platform :ios do
  before_all do
    ensure_git_status_clean
  end

  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
   match(app_identifier: 'com.thefinnternet.saywhat', type: 'development', readonly: true)
   match(app_identifier: 'com.thefinnternet.saywhat', type: 'appstore', readonly: true)
  end

  private_lane :bump_version do
    build_number = get_build_number(xcodeproj: "saywhat.xcodeproj")
    version_number = increment_version_number(bump_type: "major", xcodeproj: "saywhat.xcodeproj")  
    version_build = "v#{version_number}-#{build_number}"
    add_git_tag(tag: "testflight-#{build_number}")
  end

  desc 'Build the iOS application'
  private_lane :build do
    certificates
    cocoapods
    increment_build_number
    gym(scheme: 'saywhat', clean: true,  output_directory: './fastlane/build')
  end

  desc 'Push a new beta build to Testflight'
  lane :beta do
    #add_badge # Add beta label to icon, need to ignore icon changes before commit though
    build
    #commit_version_bump(message: 'Build Version Bump by fastlane', xcodeproj: "saywhat.xcodeproj")
    build_number = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
    #add_git_tag(tag: "testflight-#{build_number} [skip ci]")
    #push_to_git_remote
  end
end

error do |lane, exception|
  #reset_git_repo
end

# This lane is called, only if the executed lane was successful
after_all do

end
