export const AroundTheHouse = [
  'Aloha shirt',
  'Apron',
  'Apron dress',
  'Antebellum waist',
  'Ankle length Pants',
  'Anklet',
  'Armlet',
  'Babushka',
  'Baby Bonnet',
  'Baby doll dress',
  'Baggy pants',
  'Ball Gown',
  'Balmacaan',
  'Bandana',
  'Ballet skirt',
  'Barn jacket',
  'Bathing cap',
  'Bathing suit',
  'Bathrobe',
  'Bed Jacket',
  'Bell bottom',
  'Bell Boy Jacket',
  'Belt',
  'Bermuda Shorts',
  'Bertha collar',
  'Bikini',
  'Bishop sleeve',
  'Blazer',
  'Bloomer',
  'Blouse',
  'Bomber jacket',
  'Boots',
  'Bow Tie',
  'Boxers',
  'Boyfriend cut',
  'Boyfriend jeans',
  'Boyshorts',
  'Bow tie',
  'Bra',
  'Bralette',
  'Briefs',
  'Burkha',
  'Business suit',
  'Button down shirt',
  'Camisole',
  'Capri Pants',
  'Cardigan',
  'Cargos',
  'Catsuit',
  'Circle skirt',
  'Cloak',
  'Cocktail dress',
  'Compression tights',
  'Corset',
  'Cover-up',
  'Crew neck',
  'Cropped jacket',
  'Crop top',
  'Cufflinks',
  'Cummerbund',
  'Debutante dress',
  'Dress',
  'Dress Shirt',
  'Dungarees',
  'Fingerless gloves',
  'Flannel shirt',
  'Fleece',
  'Foot socks',
  'Fur coat',
  'Garter Belt',
  'Girdle',
  'Gloves',
  'Hat',
  'Hawaiian shirt',
  'Head dress',
  'Hijab',
  'Hip hugger',
  'Hoop skirt',
  'Hoody',
  'Jacket',
  'Jeans',
  'Jeggings',
  'Jogging Suit',
  'Jorts',
  'Jumper',
  'Kilt',
  'Knickers',
  'Knee high socks',
  'Leggings',
  'Leotard',
  'Lingerie',
  'Long Johns',
  'Lounge wear',
  'Lounge pants',
  'Maternity wear',
  'Mittens',
  'Nightgown',
  'Overalls',
  'Padded Bra',
  'Pajama pants',
  'Pantyhose',
  'Parkha',
  'Peacoat',
  'Pencil skirt',
  'Petticoat',
  'Polo Shirt',
  'Poncho',
  'Pullover',
  'Push up Bras',
  'Pyjamas',
  'Rain Coat',
  'Robe',
  'Romper',
  'Safari shirt',
  'Sailor pants',
  'Scarf',
  'Shirt',
  'Shorts',
  'Singlet',
  'Slip',
  'Ski Pants',
  'Skirt',
  'Short shorts',
  'Smoking jacket',
  'Socks',
  'Stockings',
  'Stirrup pants',
  'Straight skirt',
  'Stretch slip',
  'Suit',
  'Summer Cardigan',
  'Suspenders',
  'Sweater',
  'Sweatshirt',
  'Sweats',
  'Swimming Shorts',
  'Swimming Trunks',
  'T-Shirt',
  'Tank top',
  'Thigh high stockings',
  'Tie',
  'Tights',
  'Tracksuit',
  'Trainers',
  'Trench Coat',
  'Trousers',
  'Tunic',
  'Turban',
  'Turtleneck',
  'Tuxedo Jacket ',
  'Tuxedo',
  'Underwear',
  'Uniform',
  'Unitard',
  'Waistcoat',
  'Windsor Tie',
  'Chair',
  'Lift chair',
  'Bean bag',
  'Chaise longue',
  'Fauteuil',
  'Ottoman',
  'Recliner',
  'Stool',
  'Bar Stool',
  'Footstool',
  'Fainting couch',
  'Rocking chair',
  'Bar chair',
  'Multiple seats',
  'Bench',
  'Couch',
  'Love seat',
  'Chesterfield',
  'Bed',
  'Bunk bed',
  'Canopy bed',
  'Four-poster bed',
  'Murphy bed',
  'Platform bed',
  'Sleigh bed',
  'Waterbed',
  'Daybed',
  'Futon',
  'Hammock',
  'Headboard',
  'Crib',
  'Mattress',
  'Sofa bed',
  'Billiard table',
  'Chess table',
  'Entertainment center',
  'Jukebox',
  'Pinball machine',
  'Home bar',
  'Television',
  'Radio',
  'Video game console',
  'XBOX',
  'PS4',
  'Sega Genesis',
  'PC',
  'Laptops',
  'Changing table',
  'Desk',
  'Drawing board',
  'Computer desk',
  'Writing desk',
  'Lowboy',
  'Pedestal',
  'Table',
  'Game Table',
  'Coffee table',
  'Dining table',
  'End table',
  'Folding table',
  'Poker table',
  'TV tray table',
  'Wine table',
  'Washstand',
  'Workbench',
  "Baker's rack",
  'Bookcase',
  'Bathroom cabinet',
  'Chifforobe',
  'Closet',
  'Cupboard',
  'Gun cabinet',
  'Kitchen cabinet',
  'Liquor cabinet',
  'Pantry',
  'Hope chest',
  'Coat rack',
  'Drawer',
  'Hatstand',
  'Bar cabinet',
  'Filing cabinet',
  'Floating shelf',
  'Nightstand',
  'Ottoman',
  'Chest',
  'Plant',
  'Shelf',
  'Safe',
  'Umbrella',
  'Umbrella stand',
  'Wardrobe',
  'Armoire',
  'Wine rack',
  'Bedroom set ',
  'Dinette',
  'Dining set',
  'Vanity set',
  'Portable Lamp',
  'Patio set',
  'Garden bench',
  'Lamp',
  'Air conditioner',
  'Air ioniser',
  'Air purifier',
  'Aroma lamp',
  'Attic fan',
  'Bed side lamp',
  'Beverage opener',
  'Blender',
  'Camcorder',
  'Can opener',
  'Ceiling fan',
  'Central vacuum cleaner',
  'Clothes dryer',
  'Clothes iron',
  'Coffee grinder',
  'Cold-pressed juicer',
  'Combo washer dryer',
  'Computer',
  'Digital camera',
  'Dish draining closet',
  'Dishwasher',
  'DVD player',
  'Exhaust hood',
  'Garbage disposal',
  'Hair dryer',
  'Hair iron',
  'Hearth',
  'Home server',
  'Humidifier',
  'HVAC',
  'Icebox',
  'Light fixture',
  'Light',
  'Meat grinder',
  'Microwave oven',
  'Mousetrap',
  'Nightlight',
  'Oil heater',
  'Oven',
  'Patio heater',
  'Paper shredder',
  'Radiator',
  'Refrigerator',
  'Sewing machine',
  'Space heater',
  'Steam mop',
  'Stove',
  'Sump pump',
  'Telephone',
  'Toaster',
  'Toaster ovens',
  'Trouser press',
  'Vacuum cleaner',
  'Roomba',
  'Washing machine',
  'Water cooker',
  'Water purifier',
  'Water heater',
  'Solar water heater',
  'Window fan',
  'Waffle iron',
  'bathroom',
  'nook',
  'family room',
  'formal dining room',
  'foyer',
  'game room',
  'garage',
  'guest room',
  'gym',
  'H',
  'hall',
  'hallway',
  'kitchen',
  'kitchenette',
  'room',
  'nursery',
  'office',
  'panic room',
  'pantry',
  'parlor',
  'playroom',
  'pool',
  'restroom',
  'screen porch',
  'sunroom',
  'utility room',
  'Washroom',
  'Weight room',
  'Wine cellar',
  'Workroom',
  'pillow',
  'blanket',
  'sheets',
  'mattress',
  'fork',
  'spoon',
  'knife',
  'cutting board',
  'egg whisk',
  'mixing spoon',
  'napkins',
  'window',
  'fireplace',
  'chimney',
  'fence',
];

export default AroundTheHouse;
