export const Media = [
  'Africa',
  'altitude',
  'Antarctic Circle',
  'Antarctica',
  'Arctic',
  'Arctic Circle',
  'area',
  'Asia',
  'atlas',
  'Atmosphere',
  'Australia',
  'azimuth',
  'border',
  'Boundary',
  'Barrier reef',
  'capital',
  'capital city',
  'Canyon',
  'Current',
  'Coast',
  'Crag',
  'Cardinal directions',
  'cartographer',
  'cartography',
  'chart',
  'city',
  'compass rose',
  'continent',
  'contour line',
  'country',
  'degree of latitude',
  'degree of longitude',
  'Earth',
  'east',
  'Eastern Hemisphere',
  'elevation',
  'equator',
  'Europe',
  'geographic coordinates',
  'geography',
  'global',
  'globe',
  'GPS',
  'great circle',
  'hemisphere',
  'International Date Line',
  'island',
  'key',
  'kilometers',
  'land',
  'landform',
  'latitude',
  'legend',
  'longitude',
  'magnetic pole',
  'map',
  'map projection',
  'map-maker',
  'meridian',
  'miles',
  'mountain',
  'mountain range',
  'nation',
  'nautical chart',
  'north',
  'North America',
  'Magnetic Pole',
  'North Pole',
  'northeast',
  'Northern Hemisphere',
  'northwest',
  'ocean',
  'peak',
  'pole',
  'prime meridian',
  'region',
  'river',
  'scale',
  'sea',
  'sea level',
  'south',
  'South America',
  'South Pole',
  'southeast',
  'Southern Hemisphere',
  'southwest',
  'street map',
  'territory',
  'time zone',
  'topographic map',
  'topography',
  'tributary',
  'Tropic of Cancer',
  'Tropic of Capricorn',
  'tropics',
  'weather',
  'west',
  'Western Hemisphere',
  'world',
  'Acre',
  'Altitude',
  'Arid',
  'Atmosphere',
  'Azimuth',
  'Badlands',
  'Barren',
  'Basin ',
  'Bayou',
  'Bluff',
  'Canal',
  'Canyon',
  'Cavern',
  'Cay',
  'Celestial',
  'Channel',
  'Chasm',
  'Circumnavigate',
  'Cliff ',
  'Climate',
  'Coast',
  'Compass',
  'Continental divide ',
  'Contour line ',
  'Coordinate',
  'Crag',
  'Crater',
  'Creek',
  'Crevasse',
  'Crevice',
  'Current',
  'Dam',
  'Delta',
  'Desert',
  'Drought',
  'Sand Dune',
  'Earthquake',
  'Ecology',
  'Eddy',
  'Elevation',
  'Environment',
  'Equidistant',
  'Erosion',
  'Eurasia',
  'Expanse',
  'Fault line',
  'Fissure',
  'Fjord',
  'Forest',
  'Fossil',
  'Geyser',
  'Glacier',
  'Gorge',
  'Grasslands',
  'Grotto',
  'Grove',
  'Gulf',
  'Habitat',
  'Harbor',
  'Highlands',
  'Horizon',
  'Iceberg ',
  'Igneous rock',
  'Inlet',
  'Island',
  'Jungle',
  'Knoll',
  'Lagoon ',
  'Land',
  'Lava',
  'Legend',
  'Lowlands',
  'Mainland',
  'Map',
  'Marine',
  'Marsh',
  'Meadow',
  'Mesa',
  'Monsoon',
  'Nadir',
  'Oasis',
  'Oceania',
  'Overlook',
  'Ozone',
  'Peninsula',
  'Permafrost',
  'Plateau',
  'Population',
  'Prairie',
  'Rain forest ',
  'Rainfall ',
  'Range',
  'Reef ',
  'Region',
  'Sediment',
  'Seismograph',
  'Strait',
  'Tectonics ',
  'Temperatures',
  'Territory',
  'Tidal wave',
  'Tributary',
  'Tropics',
  'Tundra ',
  'Typhoon',
  'Urban',
  'Vegetation',
  'Volcano',
  'Wetlands',
  'Woodlands',
  'Zone',
];

export default Media;
