export const History = [
  'Act of Settlement',
  'Act of Union',
  'Ad Valorem',
  'Agrarian Revolution',
  'Aggression',
  'Alliance',
  'Appeal',
  'Appropriation Bill',
  'Armed Neutrality',
  'Autonomy',
  'Balance Of Trade',
  'Balance Of Power',
  'Ballot',
  'Benevolent Despotism',
  'Bill Of Rights',
  'Blockade',
  'Buffer-State',
  'Bullion',
  'Bureaucracy',
  'By Law',
  'Bye Laws',
  'Candidate',
  'Casting Vote',
  'Census',
  'Centralised Monarchy',
  'Chamber Of Commerce',
  'Chancellor of the Exchequer',
  'Charter of Liberties',
  'Chronology',
  'Circumnavigation',
  'Citizen',
  'Citizenship',
  'City Fathers',
  'Civics',
  'Civil Disobedience',
  'Civil War',
  'Coalition Ministry',
  'Code',
  'Commonwealth, The',
  'Consensus',
  'Constituency',
  'Constitution',
  'Constitutional Monarchy',
  'Constitutional Theory',
  'Constitution, Federal',
  'Consumer',
  'Contraband Articles',
  'Convention',
  'Crown Colony',
  'Crusade',
  'Culture',
  'Currency',
  'Curfew',
  'Customs Duties',
  'Deadlock, Administrative',
  'Debt Relief Act',
  'Declaration of Rights',
  'Delegate',
  'Demagogue',
  'Democracy',
  'Dependency',
  'Depreciation of Money',
  'Despotic Government',
  'Diarchy',
  'Direct Taxation',
  'Divine Right',
  'Doctrine of Lapse',
  'Domicile',
  'Doomsday Book',
  'Economic Structure',
  'Election',
  'Electorate',
  'Embassy',
  'Emigrants',
  'Emigration',
  'Empire',
  'Envoy',
  'Excommunication',
  'Executive Council',
  'Exploitation',
  'Exploration',
  'Famine Relief',
  'Fanaticism',
  'Federal Constitution',
  'Feudal System',
  'Fiduciary',
  'Fief',
  'Floating Debt',
  'Flying Shuttle',
  'Forced Loan',
  'Foreign Office',
  'Foreign Policy',
  'Franchise',
  'Freeholders',
  'Free State',
  'Free Trade',
  'Guild',
  'Gold Standard',
  'Government, Responsible',
  'Grand Alliance',
  'Grants-In-Aid',
  'Great Charter of Liberties',
  'Habeas Corpus Act',
  'High Treason',
  'Home Government',
  'Home Office',
  'Hostage',
  'Immigrants',
  'Immigration',
  'Impeachment',
  'Imperialism',
  'Incidence of Taxation',
  'Independents',
  'Individual Liberty',
  'Indulgence',
  'Industrial Revolution',
  'Initiative, Private',
  'Initiative, Public',
  'Inscription',
  'Interdict',
  'Interpellations',
  'Joint Stock Company',
  'Journey Man',
  'Judicial Service',
  'Jurisdiction',
  'Labour, Division Of',
  'Labour Legislation',
  'Laissez-Faire',
  'Land Tenure',
  'Legal Tender',
  'Legislative Council',
  'Letters Patent',
  'Liberty of The Press',
  'Limited Liability',
  'Limited Monarchy',
  'Magna Carta',
  'Mandatory State',
  'Manorial System',
  'Martial Law',
  'Military Occupation',
  'Minority Minute (To Record in A Minute Book)',
  'Mobocracy',
  'Negotiation',
  'Neolithic Age',
  'No-Confidence Motion',
  'Nomination',
  'Non-Aggression',
  'Non-Co-Operation',
  'Non-Intervention Policy',
  'Non-Official Element',
  'No Tax Campaign',
  'Opposition, The',
  'Orders in Council',
  'Ordinance',
  'Palaeolithic Age',
  'Passive Resistance',
  'Petition of Right',
  'Policy',
  'Poor Rate',
  'Preferential Tariff',
  'Protective Duties',
  'Protective Tariff',
  'Rate Payers',
  'Reforms Act',
  'Regulating Act',
  'Reign Of Terror',
  'The Renaissance',
  'Representative Government',
  'Responsible Government',
  'Round Table Conference',
  'Senate',
  'Service, Secret',
  'Sinking Fund',
  'Squire',
  'Standard of Life',
  'Standing Army',
  'Standing Committee',
  'Standing Orders',
  'Stock and Land Lease System',
  'Subject, Reserved',
  'Subject, Transferred',
  'Subsidiary System',
  'Suffrage',
  'Tariffs',
  'Tax',
  'Temperance',
  'Tenant',
  'Tolls',
  'Trade Union',
  'Unitary Constitution',
  'Vested Interests',
  'Veto',
  'White-Paper',
  'Working Committee',
  'World Court',
  'Write Of Habeas Corpus',
  'Abbey',
  'Accession',
  'Ale',
  'Alliance',
  'Allies',
  'Altar',
  'Anachronism',
  'Angles',
  'Anglo-Saxon',
  'Annates',
  'Annex',
  'Appeasement',
  'Archbishop',
  'Aristocracy',
  'Armada',
  'Armed Forces',
  'Armistice',
  'Arms Race',
  'Army',
  'Assassinate',
  'Axis',
  'Banish',
  'Baron',
  'Barracks',
  'Battle',
  'Beef Bonanza',
  'Bishop',
  'Black Hand',
  'Blitzkrieg',
  'Bolt Hole',
  'Bomb',
  'Brinkmanship',
  'Bronze Age',
  'Bunker',
  'Cannon',
  'Capture',
  'Cardinal',
  'Catapult',
  'Catholic',
  'Cede',
  'Chancellor',
  'Chantries',
  'Civil War',
  'Clergy',
  'Colonise',
  'Colony',
  'Commander',
  'Communication Trench',
  'Confederate',
  'Conscription',
  'Convent',
  'Coronation',
  'Counter Offensive',
  'Counter Reformation',
  'Court/Courtiers',
  'Cow Town',
  'Cowboy',
  'Culture',
  'Danelaw',
  'Danes',
  'Declare War',
  'Defeat',
  'Democracy',
  'Depose',
  'Deserving Poor',
  'Diet',
  'Divine Right of Kings',
  'Dogfight',
  'Domesday Book',
  'Duck Boards',
  'Duke',
  'Dulag',
  'Earl',
  'Ecclesiastical Court',
  'Economy',
  'elongated',
  'Emigrate',
  'Empire',
  'Enemy',
  'Exchequer',
  'Excommunicate',
  'Exile',
  'Federation',
  'Field Gun',
  'Fire Ship',
  'Fire Step',
  'Force',
  'Forest Law',
  'Fort',
  'Free Trade',
  'Frontier',
  'Fuhrer',
  'Fyrd',
  'Geneva Convention',
  'Gestapo',
  'Government',
  'Grand Remonstrance',
  'Habeas Corpus',
  'Heir',
  'Heresy/Heretic',
  'Historian',
  'Holy Relic',
  'Holy Roman Empire',
  'Homestead Act 1862',
  'Homesteader',
  'Imperialism',
  'Indulgences',
  'Industrialisation',
  'Infantry',
  'Infidel',
  'Inherit',
  'Internment',
  'Interregnum',
  'Invasion, To Invade',
  'Iron Age',
  'Judiciary',
  'Jurisdiction',
  'Justice of the Peace',
  'Justiciar',
  'Jute',
  'Lay Court',
  'Legatine Court',
  'Luftwaffe',
  'Machine Gun',
  'Marlag',
  'Mass',
  'Mediate',
  'Merchant',
  'Mercia',
  'Militarism',
  'Monastery',
  'Mountain Man',
  'Mycenaean',
  'Nationalism',
  'Nazi',
  'Nineteen Proposals',
  'Nissen Hut',
  'Norman',
  'Occupation/ To occupy',
  'Oflag',
  'Open Range',
  'Outpost',
  'Papal Bull',
  'Papal Curia',
  'Papal Dispensation',
  'Parados',
  'Parapet',
  'Parish',
  'Parliament',
  'Partition',
  'Peter&#039;s Pence',
  'Phoney War',
  'Pilgrimage',
  'Pioneer',
  'Plains',
  'Pope',
  'Pottage',
  'Prisoner of War',
  'Prisoner of War Camp',
  'Privy Council',
  'Progress',
  'Protector',
  'Protestant',
  'Purgatory',
  'Puritan',
  'Raid',
  'Ranch',
  'Re-unification',
  'Rebellion',
  'Red Cross',
  'Reform',
  'Reformation',
  'Regency/Regent',
  'Relic',
  'Reservation',
  'Restoration',
  'Retreat',
  'Revolution',
  'Rifle',
  'Sack',
  'Saxon',
  'Schism',
  'Schleiffen Plan',
  'Schutzstaffel (Nazi SS)',
  'Secular',
  'Serviceman',
  'Settler',
  'Shell',
  'Shield Wall',
  'Siege',
  'Slander',
  'Soldier',
  'Sovereign',
  'Stalag/Stalag Luft',
  'State',
  'Stone Age',
  'Stronghold',
  'Subject',
  'Submarine',
  'Succeed',
  'Sump',
  'Support Trench',
  'Tank',
  'Tax',
  'Territory',
  'Terrorism',
  'Test Acts',
  'Thegn (Thane)',
  'Tithe',
  'Titled',
  'Torpedo',
  'Trading Post',
  'Treason',
  'Treaty',
  'Trench',
  'Trench Block',
  'Trench Foot',
  'Tribe',
  'Trojan',
  'Troops',
  'Tyrant',
  'U Boat',
  'Usurp',
  'H Bomb',
  'Kamakazi',
  'Vestments',
  'Vikings',
  'War',
  'Weapon',
  'Western Front',
  'WWI',
  'WWII',
  'WWIII',
  'World War',
  'Yeoman',
  'Zeppelin',
];

export default History;
