export const Media = [
  'Planet Earth',
  'Band of Brothers',
  'Chernobyl',
  'Breaking Bad',
  'Blue Planet II',
  'The Wire',
  'Game of Thrones',
  'Our Planet',
  'Cosmos',
  'Cosmos',
  'Rick and Morty',
  'Avatar: The Last Airbender',
  'The Sopranos',
  'The World at War',
  'Life',
  'Sherlock',
  'The Vietnam War',
  'Fullmetal Alchemist: Brotherhood',
  'The Beatles Anthology',
  'The Twilight Zone',
  'Human Planet',
  'The Blue Planet',
  'Firefly',
  'Batman: The Animated Series',
  'Dekalog',
  'Frozen Planet',
  'True Detective',
  'The Civil War',
  'Death Note',
  'Fargo',
  'Apocalypse: The Second World War',
  'When They See Us',
  'Sahsiyet',
  'Cowboy Bebop',
  'Africa',
  'Last Week Tonight with John Oliver',
  'TVF Pitchers',
  'Only Fools and Horses',
  'Friends',
  "Monty Python's Flying Circus",
  'Das Boot',
  'Hunter x Hunter',
  'Black Mirror',
  'Pew News',
  'Pride and Prejudice',
  'Seinfeld',
  'The Office',
  'Gravity Falls',
  'One Punch Man',
  'Over the Garden Wall',
  'Stranger Things',
  'Twin Peaks',
  'Narcos',
  'Peaky Blinders',
  'The Boys',
  'Freaks and Geeks',
  'Blackadder Goes Forth',
  'Nathan for You',
  'Arrested Development',
  'Fawlty Towers',
  'House of Cards',
  'Rome',
  'Westworld',
  'Black Sun',
  'Content Cop',
  'Cobra Kai',
  "Chappelle's Show",
  "It's Always Sunny in Philadelphia",
  'Oz',
  'Attack on Titan',
  'The West Wing',
  'Dragon Ball Z',
  'Steins;Gate',
  'Dragon Ball Z',
  'I, Claudius',
  'Sarabhai vs Sarabhai',
  'The Marvelous Mrs. Maisel',
  'Leyla and Mecnun',
  'Easy Living',
  'Justice League Unlimited',
  'The Jinx: The Life and Deaths of Robert Durst',
  'Kota Factory',
  'Mahabharat',
  'The Adventures of Sherlock Holmes',
  'Dark',
  'Six Feet Under',
  'Curb Your Enthusiasm',
  'The Simpsons',
  'South Park',
  'The Thick of It',
  'House',
  'The Return of Sherlock Holmes',
  'The Crown',
  'The Haunting of Hill House',
  'Battlestar Galactica',
  'This Is Us',
  'Better Call Saul',
  'Top Gear',
  'Fleabag',
  'Critical Role',
  'The Promised Neverland',
  'Satyamev Jayate',
  'Deadwood',
  'Wan pîsu',
  'The Shield',
  'Downton Abbey',
  'The Grand Tour',
  'Lonesome Dove',
  'Berserk',
  'Sacred Games',
  'Archer',
  'Blackadder II',
  'The Memoirs of Sherlock Holmes',
  'The X-Files',
  'Young Justice',
  'Bron/Broen',
  'Parks and Recreation',
  'Battlestar Galactica',
  'Star Trek: The Next Generation',
  'Friday Night Lights',
  'Dexter',
  'Atlanta',
  'Daredevil',
  'Samurai X: Trust and Betrayal',
  'Code Geass: Lelouch of the Rebellion',
  'Gomorra',
  'Making a Murderer',
  'The Dark Crystal: Age of Resistance',
  'Through the Wormhole',
  'Blackadder the Third',
  'QI',
  'Mad Men',
  'North & South',
  'Mindhunter',
  'Line of Duty',
  'The Bugs Bunny Show',
  'Long Way Round',
  'BoJack Horseman',
  'Yeh Meri Family',
  'El Chavo del Ocho',
  'Father Ted',
  'Peep Show',
  'Shameless',
  'Love, Death & Robots',
  'Skam',
  'Doctor Who',
  'The Eric Andre Show',
  'Spaced',
  'The Newsroom',
  'Mind Your Language',
  'The Untold History of the United States',
  'From the Earth to the Moon',
  "Chef's Table",
  'Brass Eye',
  'Monster',
  'Yes Minister',
  'Behzat Ç.: Bir Ankara Polisiyesi',
  'Fullmetal Alchemist',
  "Mister Rogers' Neighborhood",
  'The Family Man',
  'Neon Genesis Evangelion',
  'Justified',
  'Justice League',
  'Samurai Champloo',
  "Agatha Christie's Poirot",
  'Adventure Time',
  'Dragon Ball',
  'The Defiant Ones',
  'Boardwalk Empire',
  'Queer Eye',
  'Mystery Science Theater 3000',
  'Dragon Ball',
  'Big Little Lies',
  'Flight of the Conchords',
  'Louie',
  'Generation Kill',
  'The Night Of',
  'Coupling',
  'Yes, Prime Minister',
  'The IT Crowd',
  'Twin Peaks',
  'Formula 1: Drive to Survive',
  'Alfred Hitchcock Presents',
  'Silicon Valley',
  'The Punisher',
  'Impractical Jokers',
  'Horace and Pete',
  'Unbelievable',
  'Mr. Bean',
  'Vikings',
  'Spartacus: Gods of the Arena',
  'Whose Line Is It Anyway?',
  'John Adams',
  'Homicide: Life on the Street',
  'Endeavour',
  'The Office',
  'Hannibal',
  'The New Batman Adventures',
  'Black Books',
  "Dr. Horrible's Sing-Along Blog",
  'Sons of Anarchy',
  "I'm Alan Partridge",
  'Mr. Robot',
  'Umbre',
  'Detectorists',
  'Luther',
  'Spartacus',
  'Your Lie in April',
  'Feud: Bette and Joan',
  'Erased',
  'Goblin',
  'Rurouni Kenshin: Wandering Samurai',
  'Between Two Ferns with Zach Galifianakis',
  'My Hero Academia',
  'Money Heist',
  'Ghost in the Shell: Stand Alone Complex',
  'My Brilliant Friend',
  'The Knick',
  'Rake',
  'Letterkenny',
  'The Venture Bros.',
  'Clannad: After Story',
  'Community',
  'Naruto: Shippûden',
  'Masum',
  'American Crime Story',
  "The Handmaid's Tale",
  "This Is England '90",
  'Wentworth',
  'Generation War',
  'Samurai Jack',
  'Futurama',
  'Mushi-Shi',
  'Kardes Payi',
  'X-Men: The Animated Series',
  'Ash vs Evil Dead',
  'Brideshead Revisited',
  'Pose',
  'Scenes from a Marriage',
  'The Angry Video Game Nerd',
  'House of Cards',
  'The Shawshank Redemption	',
  'The Godfather	',
  'The Dark Knight	',
  'The Godfather: Part II	',
  'Joker	',
  'The Lord of the Rings: The Return of the King	',
  'Pulp Fiction	',
  "Schindler's List	",
  'Inception	',
  'Fight Club	',
  'The Lord of the Rings: The Fellowship of the Ring	',
  'Forrest Gump	',
  'The Good, the Bad and the Ugly	',
  'The Lord of the Rings: The Two Towers	',
  'The Matrix	',
  'Goodfellas	',
  'Star Wars: Episode V - The Empire Strikes Back	',
  "One Flew Over the Cuckoo's Nest	",
  'Harakiri	',
  'Ayla: The Daughter of War	',
  'Drishyam	',
  'Interstellar	',
  'City of God	',
  'Spirited Away	',
  'Saving Private Ryan	',
  'The Green Mile	',
  'Life Is Beautiful	',
  'Se7en	',
  'The Silence of the Lambs	',
  'Star Wars: Episode IV - A New Hope	',
  'Seven Samurai	',
  "It's a Wonderful Life	",
  'Parasite	',
  'Avengers: Endgame	',
  'Avengers: Infinity War	',
  'Whiplash	',
  'The Intouchables	',
  'The Prestige	',
  'The Departed	',
  'The Pianist	',
  'Gladiator	',
  'American History X	',
  'The Usual Suspects	',
  'Léon: The Professional	',
  'The Lion King	',
  'Terminator 2: Judgment Day	',
  'Cinema Paradiso	',
  'Grave of the Fireflies	',
  'Back to the Future	',
  'Once Upon a Time in the West	',
  'Psycho	',
  'Rear Window	',
  'Casablanca	',
  'The Great Dictator	',
  'Modern Times	',
  'City Lights	',
  'Uri: The Surgical Strike	',
  'Capernaum	',
  'Andhadhun	',
  'Your Name.	',
  'Dangal	',
  'Spider-Man: Into the Spider-Verse	',
  'Coco	',
  'Django Unchained	',
  'The Dark Knight Rises	',
  'Like Stars on Earth	',
  'WALL·E	',
  'The Lives of Others	',
  'Oldboy	',
  'Memento	',
  'Princess Mononoke	',
  'Aliens	',
  'Once Upon a Time in America	',
  'Raiders of the Lost Ark	',
  'The Shining	',
  'Apocalypse Now	',
  'Alien	',
  'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb	',
  'Witness for the Prosecution	',
  'Paths of Glory	',
  'Sunset Blvd.	',
  'The Hunt	',
  'A Separation	',
  'Incendies	',
  'My Father and My Son	',
  'Toy Story 3	',
  'Inglourious Basterds	',
  'Eternal Sunshine of the Spotless Mind	',
  'Amélie	',
  'Snatch	',
  'Requiem for a Dream	',
  'American Beauty	',
  'Good Will Hunting	',
  'Children of Heaven	',
  'The Bandit	',
  'Toy Story	',
  'Braveheart	',
  'Reservoir Dogs	',
  '	',
  'The Dark Knight	',
  'Toy Story 4	',
  'Parasite	',
  'Once Upon a Time in Hollywood	',
  'Zombieland	',
  'Avengers: Endgame	',
  'Spider-Man: Far from Home	',
  'The Shawshank Redemption	',
  'Taxi Driver	',
  'John Wick: Chapter 3 - Parabellum	',
  'Her	',
  'Gladiator	',
  'The Dark Knight Rises	',
  'The Shining	',
  'The Godfather	',
  'Batman Begins	',
  'Pulp Fiction	',
  'Bohemian Rhapsody	',
  'The Lion King	',
  'Alien	',
  'Spider-Man: Into the Spider-Verse	',
  'Fight Club	',
  'Green Book	',
  'A Star Is Born	',
  "Harry Potter and the Sorcerer's Stone	",
  'Interstellar	',
  'Watchmen	',
  'Halloween	',
  'Inception	',
  'Avengers: Infinity War	',
  'The Terminator	',
  'Blade Runner 2049	',
  'The Wolf of Wall Street	',
  'Mad Max: Fury Road	',
  'Terminator 2: Judgment Day	',
  'The Nightmare Before Christmas	',
  'Apocalypse Now	',
  'Deadpool 2	',
  'The Fifth Element	',
  'Walk the Line	',
  'The Matrix	',
  'Goodfellas	',
  'The Lord of the Rings: The Fellowship of the Ring	',
  'Thor: Ragnarok	',
  'The King of Comedy	',
  'Get Out	',
  'The Silence of the Lambs	',
  'Forrest Gump	',
  'Kingsman: The Secret Service	',
  'The Departed	',
  'Titanic	',
  'Call Me by Your Name	',
  'Se7en	',
  'Mission: Impossible - Fallout	',
  'The Exorcist	',
  'American Psycho	',
  'American Beauty	',
  'Gone Girl	',
  "Schindler's List	",
  'Léon: The Professional	',
  'Requiem for a Dream	',
  'Back to the Future	',
  'The Goonies	',
  'Prisoners	',
  'The Favourite	',
  'Hotel Mumbai	',
  'The Godfather: Part II	',
  'Baby Driver	',
  'Psycho	',
  'The Lord of the Rings: The Return of the King	',
  'Dunkirk	',
  'Superbad	',
  'Ghostbusters	',
  'Avatar	',
  'Jurassic Park	',
  'Jaws	',
  'The Prestige	',
  'Stand by Me	',
  'Rogue One: A Star Wars Story	',
  'The Handmaiden	',
  'Love Actually	',
  'There Will Be Blood	',
  'Coco	',
  'Black Swan	',
  'Shutter Island	',
  'Scarface	',
  'The Princess Bride	',
  'A Clockwork Orange	',
  'Braveheart	',
  'La La Land	',
  'Guardians of the Galaxy	',
  'Logan	',
  'No Country for Old Men	',
  'Django Unchained	',
  'Harry Potter and the Goblet of Fire	',
  'Hacksaw Ridge	',
  'Deadpool	',
  'The Notebook	',
  'Whiplash	',
  'Catch Me If You Can	',
  'The Revenant	',
  'Spirited Away	',
  'Dazed and Confused	',
  'Blade Runner	',
  'The Green Mile	',
  'Saving Private Ryan	',
  'Star Wars: Episode IV - A New Hope	',
  "One Flew Over the Cuckoo's Nest	",
  'Zodiac	',
  'Moana	',
  'Full Metal Jacket	',
  'Arrival	',
  'Good Will Hunting	',
  'The Hateful Eight	',
  'The Big Short	',
  'About Time	',
  'The Good, the Bad and the Ugly	',
  'Brokeback Mountain	',
  'Shaun of the Dead	',
  'Pride & Prejudice	',
  'The Big Lebowski	',
  'Harry Potter and the Prisoner of Azkaban	',
  'Sin City	',
  'Mulholland Drive	',
  'The Hangover	',
  'American History X	',
  'Three Billboards Outside Ebbing, Missouri	',
  'Toy Story	',
  'The Avengers	',
  'Tombstone	',
  'The Machinist	',
  'The Thing	',
  'Blow	',
  'What We Do in the Shadows	',
  'Sicario	',
  'Back to the Future Part II	',
  'Trainspotting	',
  'The Grand Budapest Hotel	',
  'Coraline	',
  'Birdman or (The Unexpected Virtue of Ignorance)	',
  'Lost in Translation	',
  'The Usual Suspects	',
  'The Lord of the Rings: The Two Towers	',
  'The Sixth Sense	',
  "Rosemary's Baby	",
  'Cast Away	',
  'The Social Network	',
  'Room	',
  'Casino	',
  'Oldboy	',
  'Aliens	',
  'The Wizard of Oz	',
  'Reservoir Dogs	',
  'The Martian	',
  'Donnie Darko	',
  'Edge of Tomorrow	',
  'V for Vendetta	',
  'Heat	',
  'Iron Man	',
  'Star Wars: Episode VII - The Force Awakens	',
  'The Breakfast Club	',
  'The Imitation Game	',
  'Saw	',
  "Ocean's Eleven	",
  'Drive	',
  'Pirates of the Caribbean: The Curse of the Black Pearl	',
  "Pan's Labyrinth	",
  'Raging Bull	',
  'Ex Machina	',
  'Kill Bill: Vol. 1	',
  'Capernaum	',
  'The Pursuit of Happyness	',
  'Edward Scissorhands	',
  'Memento	',
  'The Graduate	',
  'Snatch	',
  'The Girl with the Dragon Tattoo	',
  'Mystic River	',
  'Stardust	',
  'Apocalypto	',
  'City of God	',
  'E.T. the Extra-Terrestrial	',
  'Remember the Titans	',
  'Once Upon a Time in America	',
  'Gangs of New York	',
  'Unforgiven	',
  'Zootopia	',
  'Inside Man	',
  'Guardians of the Galaxy Vol. 2	',
  'Eternal Sunshine of the Spotless Mind	',
  'The Hobbit: An Unexpected Journey	',
  'Harry Potter and the Half-Blood Prince	',
  'Mary Poppins	',
  'Moulin Rouge!	',
  'Rear Window	',
  'Life Is Beautiful	',
  'Wind River	',
  'Fury	',
  'Star Wars: Episode V - The Empire Strikes Back	',
  'Toy Story 3	',
  'Incredibles 2	',
  'Captain America: Civil War	',
  'Home Alone	',
  'Raiders of the Lost Ark	',
  'Airplane!	',
  'Your Name.	',
  'X-Men: First Class	',
  'Dances with Wolves	',
  'A Beautiful Mind	',
  'Warrior	',
  'Aladdin	',
  'Moneyball	',
  'First Blood	',
  'American Gangster	',
  'Blue Is the Warmest Color	',
  'Little Miss Sunshine	',
  'Boogie Nights	',
  'Apollo 13	',
  'Into the Wild	',
  'Nightcrawler	',
  'The Impossible	',
  'Interview with the Vampire: The Vampire Chronicles	',
  'The Pianist	',
  'The Help	',
  'Minority Report	',
  'Memories of Murder	',
  "Ferris Bueller's Day Off	",
  'The Intouchables	',
  'Star Wars: Episode VI - Return of the Jedi	',
  'Casino Royale	',
  'Seven Samurai	',
  'The Incredibles	',
  'Black Hawk Down	',
  'Dallas Buyers Club	',
  'Star Trek	',
  'True Romance	',
  'Skyfall	',
  'Predator	',
  'Atonement	',
  'The Sound of Music	',
  'Die Hard	',
  'Hot Fuzz	',
  'The Curious Case of Benjamin Button	',
  'Crash	',
  'Fargo	',
  'As Good as It Gets	',
  'Harry Potter and the Deathly Hallows: Part 1	',
  'Young Frankenstein	',
  'Monsters, Inc.	',
  'Silver Linings Playbook	',
  'The Deer Hunter	',
  'Indiana Jones and the Last Crusade	',
  'Taken	',
  'The Perks of Being a Wallflower	',
  'In Bruges	',
  'Spotlight	',
  'Rocky	',
  'The Crow	',
  'Shrek	',
  'The Invisible Guest	',
  'The Lives of Others	',
  'Tangled	',
  'The Blind Side	',
  'Captain America: The Winter Soldier	',
  'Billy Elliot	',
  'Roma	',
  'Chinatown	',
  'Inside Out	',
  'The Godfather: Part III	',
  'Platoon	',
  'Gravity	',
  'Almost Famous	',
  'The Truman Show	',
  'The Town	',
  'Sherlock Holmes	',
  'Lion	',
  'X-Men: Days of Future Past	',
  'Clerks	',
  'Amélie	',
  'Gone with the Wind	',
  'Children of Men	',
  'The Game	',
  'Slumdog Millionaire	',
  'The Warriors	',
  'Life of Pi	',
  'Casablanca	',
  'Captain Fantastic	',
  'The Hunt	',
  '	',
  'Vertigo	',
  'When Harry Met Sally...	',
  'Kill Bill: Vol. 2	',
  'Scent of a Woman	',
  'Ratatouille	',
  'Evil Dead II	',
  'RoboCop	',
  'The Name of the Rose	',
  'Argo	',
  'Falling Down	',
  'Boyz n the Hood	',
  'True Grit	',
  'The Others	',
  'Searching	',
  'Blazing Saddles	',
  'The Hobbit: The Desolation of Smaug	',
  'Harakiri	',
  'Up	',
  'Amadeus	',
  'Once Upon a Time in the West	',
  'Training Day	',
  'Office Space	',
  "The King's Speech	",
  'Citizen Kane	',
  'Lock, Stock and Two Smoking Barrels	',
  'The Little Mermaid	',
  'Toy Story 2	',
  'Midnight in Paris	',
  'The Bourne Identity	',
  'Manchester by the Sea	',
  'Grave of the Fireflies	',
  'Blue Velvet	',
  'Big Fish	',
  'Nosferatu	',
  'Moonrise Kingdom	',
  'District 9	',
  'Dangal	',
  "It's a Wonderful Life	",
  'Hunt for the Wilderpeople	',
  'Hidden Figures	',
  'WALL·E	',
  'Monty Python and the Holy Grail	',
  'Sleepers	',
  'Mad Max 2: The Road Warrior	',
  'Hell or High Water	',
  'The Fly	',
  'Laura	',
  'Stalker	',
  'The Hunt for Red October	',
  'Close Encounters of the Third Kind	',
  'Primal Fear	',
  'The Last of the Mohicans	',
  'Groundhog Day	',
  'The Fighter	',
  'The Blues Brothers	',
  'Finding Nemo	',
  'L.A. Confidential	',
  'The Holy Mountain	',
  'Do the Right Thing	',
  'Changeling	',
  'Million Dollar Baby	',
  'Gran Torino	',
  'Willy Wonka & the Chocolate Factory	',
  'Magnolia	',
  'Serenity	',
  'Sense and Sensibility	',
  'The Fault in Our Stars	',
  'Shoplifters	',
  'Incendies	',
  'Only the Brave	',
  'Dangerous Liaisons	',
  'Indiana Jones and the Temple of Doom	',
  'The Birds	',
  'Rain Man	',
  'The Untouchables	',
  'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb	',
  'My Cousin Vinny	',
  'The Theory of Everything	',
  "Howl's Moving Castle	",
  'The Last Samurai	',
  'The Hurt Locker	',
  'Andhadhun	',
  'Night of the Living Dead	',
  'The Secret of NIMH	',
  'Lolita	',
  'Isle of Dogs	',
  'Creed	',
  "What's Eating Gilbert Grape	",
  'Seven Pounds	',
  'Hotel Rwanda	',
  'Big Hero 6	',
  'How to Train Your Dragon	',
  'The Florida Project	',
  'The Sandlot	',
  'A Streetcar Named Desire	',
  'Y Tu Mamá También	',
  'Downfall	',
  'The Butterfly Effect	',
  'Dirty Harry	',
  'Some Like It Hot	',
  'Barry Lyndon	',
  'Fear and Loathing in Las Vegas	',
  'Gattaca	',
  'O Brother, Where Art Thou?	',
  'Star Trek Into Darkness	',
  'The Skin I Live In	',
  'To Kill a Mockingbird	',
  'A Few Good Men	',
  'The Bourne Supremacy	',
  'Princess Mononoke	',
  'Boyhood	',
  'Deliverance	',
  'The Reader	',
  'The Boondock Saints	',
  'Beauty and the Beast	',
  'Road to Perdition	',
  'Dark City	',
  'Wreck-It Ralph	',
  'Sling Blade	',
  'Mulan	',
  'Mr. Nobody	',
  'Traffic	',
  'I Saw the Devil	',
  'Gifted	',
  'The Secret in Their Eyes	',
  'Moon	',
  "Breakfast at Tiffany's	",
  'The Magnificent Seven	',
  'Dawn of the Dead	',
  'Crouching Tiger, Hidden Dragon	',
  'Brazil	',
  'Blood Diamond	',
  'Come and See	',
  'The Fugitive	',
  'Let the Right One In	',
  'Philadelphia	',
  'The Boy in the Striped Pajamas	',
  'The Royal Tenenbaums	',
  'Metropolis	',
  'Gone Baby Gone	',
  'The Bourne Ultimatum	',
  'Mother	',
  'Kung Fu Panda	',
  'A Bronx Tale	',
  'This Is Spinal Tap	',
  'The Piano	',
  'The Big Sick	',
  'Before Sunrise	',
  'Das Boot	',
  'Dawn of the Planet of the Apes	',
  "Singin' in the Rain	",
  'The Abyss	',
  'The Fall	',
  'Who Framed Roger Rabbit	',
  'Midnight Cowboy	',
  'Match Point	',
  'The Sting	',
  'The Great Escape	',
  'The Seventh Seal	',
  'The Wrestler	',
  'The Thin Red Line	',
  'Fried Green Tomatoes	',
  "National Lampoon's Christmas Vacation	",
  'The Count of Monte Cristo	',
  "Sophie's Choice	",
  'Fantastic Mr. Fox	',
  'The Outlaw Josey Wales	',
  'Bridge of Spies	',
  'Dog Day Afternoon	',
  'Cinema Paradiso	',
  'Lost Highway	',
  'Donnie Brasco	',
  'Frankenstein	',
  'End of Watch	',
  'Ghost in the Shell	',
  'Akira	',
  'North by Northwest	',
  'Man on Fire	',
  'Planet of the Apes	',
  'Solaris	',
  'Straight Outta Compton	',
  'Blood In, Blood Out	',
  'The Girl with the Dragon Tattoo	',
  'The Elephant Man	',
  'Spartacus	',
  'The Bridge on the River Kwai	',
  'In the Mood for Love	',
  'The Lego Movie	',
  'Cabaret	',
  'Papillon	',
  'Snow White and the Seven Dwarfs	',
  'Invasion of the Body Snatchers	',
  'My Neighbor Totoro	',
  'M	',
  'Network	',
  'Captain Phillips	',
  'Lord of War	',
  'Wild Tales	',
  "Monty Python's Life of Brian	",
  'Despicable Me	',
  'After Hours	',
  'Midnight Express	',
  'The Iron Giant	',
  'Short Term 12	',
  'Naked	',
  'Lethal Weapon	',
  'Annie Hall	',
  'Awakenings	',
  'Chaplin	',
  'Empire of the Sun	',
  'Ben-Hur	',
  'Eastern Promises	',
  'Modern Times	',
  'Munich	',
  'Enemy at the Gates	',
  'Being John Malkovich	',
  'Stranger Than Fiction	',
  "Kelly's Heroes	",
  'Giant	',
  'The Illusionist	',
  'Flipped	',
  "Carlito's Way	",
  'Cold War	',
  'The Jungle Book	',
  'Dogville	',
  'Butch Cassidy and the Sundance Kid	',
  'Ed Wood	',
  'A Separation	',
  'Baahubali: The Beginning	',
  "Hachi: A Dog's Tale	",
  'Glengarry Glen Ross	',
  'Kiss Kiss Bang Bang	',
  'Goldfinger	',
  'Battle Royale	',
  'The Raid: Redemption	',
  'Sing Street	',
  'My Fair Lady	',
  'Funny Games	',
  'Wings of Desire	',
  'Kramer vs. Kramer	',
  'PK	',
  'Sunset Blvd.	',
  '	',
  'Like Stars on Earth	',
  'Die Hard with a Vengeance	',
  'The Body	',
  'The Man from Earth	',
  'King Kong	',
  'A Silent Voice	',
  'JFK	',
  'For a Few Dollars More	',
  'Serpico	',
  'Rise of the Planet of the Apes	',
  'Adaptation.	',
  'October Sky	',
  'The Naked Gun: From the Files of Police Squad!	',
  'The Color Purple	',
  'Kung Fu Hustle	',
  'Glory	',
  'How to Train Your Dragon 2	',
  'Paris, Texas	',
  'The Best Offer	',
  'The Ten Commandments	',
  'The Apartment	',
  'Doctor Zhivago	',
  'Shane	',
  'Bride of Frankenstein	',
  'The Life of David Gale	',
  'Perfect Blue	',
  'Lucky Number Slevin	',
  'Synecdoche, New York	',
  'Robin Hood	',
  'A Christmas Story	',
  'The Insider	',
  'Gangs of Wasseypur	',
  'Freaks	',
  'Before Sunset	',
  'A Fistful of Dollars	',
  'Pink Floyd: The Wall	',
  'Paths of Glory	',
  'In the Name of the Father	',
  'Rebecca	',
  'Ordinary People	',
  'Kubo and the Two Strings	',
  'Deep Red	',
  'Enter the Dragon	',
  'La Haine	',
  'The Conversation	',
  'I Am Sam	',
  'Cool Hand Luke	',
  'Bonnie and Clyde	',
  '	',
  'Joker	',
  'Once Upon a Time in Hollywood	',
  'Parasite	',
  'Spider-Man: Far from Home	',
  'John Wick: Chapter 3 - Parabellum	',
  'Avengers: Endgame	',
  'Toy Story 4	',
  'Capernaum	',
  'Andhadhun	',
  'Shoplifters	',
  'K.G.F: Chapter 1	',
  'Searching	',
  'Green Book	',
  'Cold War	',
  'Roma	',
  'Deadpool 2	',
  'Hotel Mumbai	',
  'Isle of Dogs	',
  'The Favourite	',
  'Mission: Impossible - Fallout	',
  'Spider-Man: Into the Spider-Verse	',
  'Avengers: Infinity War	',
  'Incredibles 2	',
  'Bohemian Rhapsody	',
  'A Star Is Born	',
  'Ayla: The Daughter of War	',
  'Call Me by Your Name	',
  'The Florida Project	',
  'The Big Sick	',
  'Wind River	',
  'Get Out	',
  'Three Billboards Outside Ebbing, Missouri	',
  'Dunkirk	',
  'Baahubali 2: The Conclusion	',
  'Gifted	',
  'Paddington 2	',
  'Guardians of the Galaxy Vol. 2	',
  'Baby Driver	',
  'Only the Brave	',
  'Thor: Ragnarok	',
  'Logan	',
  'Loving Vincent	',
  'Wonder	',
  'Coco	',
  'Blade Runner 2049	',
  'Pink	',
  'A Silent Voice	',
  'Your Name.	',
  'The Salesman	',
  'Queen',
  "Guns N' Roses",
  'Nirvana',
  'John Lennon',
  'John Farnham',
  'Led Zeppelin',
  'Prince',
  'AC/DC',
  'Michael Jackson',
  'The Rolling Stones',
  'ABBA',
  'Bon Jovi',
  'The Easybeats',
  'Madonna',
  'The Beach Boys',
  'Bob Dylan',
  'Eagles',
  'George Michael',
  'U2',
  'Aretha Franklin',
  'Whitney Houston',
  'Gotye, Kimbra',
  'Deep Purple',
  'Crowded House',
  'The Doors',
  'Men At Work',
  'Oasis',
  'Marvin Gaye',
  'Cold Chisel',
  'Bee Gees',
  'Beyoncé',
  'Spice Girls',
  'Stevie Wonder',
  'Kylie Minogue',
  'Red Hot Chili Peppers',
  'Meat Loaf',
  'Culture Club',
  'Robbie Williams',
  'Fleetwood Mac',
  'Metallica',
  'Elvis Presley',
  'INXS',
  'David Bowie',
  'Jeff Buckley',
  'Cyndi Lauper',
  'Pink Floyd',
  'Yothu Yindi',
  'Don McLean',
  "Sinéad O'Connor",
  'Carly Simon',
  'Jimi Hendrix',
  'Green Day',
  'Blondie',
  'Mark Ronson, Bruno Mars',
  'The Jacksons',
  'Paul Simon',
  'Hunters & Collectors',
  'Billy Joel',
  'Jimmy Barnes',
  'Eminem',
  'Joy Division',
  'Savage Garden',
  'Phil Collins',
  'Britney Spears',
  'The Knack',
  'R.E.M.',
  'Elton John',
  'Bruce Springsteen',
  'Salt-N-Pepa',
  'Daddy Cool',
  'Powderfinger',
  'Paul McCartney',
  'Pearl Jam',
  'Adele',
  'Midnight Oil',
  'Radiohead',
  'The Clash',
  'Take That',
  'ICEHOUSE',
  'Coldplay',
  'Gloria Gaynor',
  'Fugees',
  'The Police',
  'Eric Clapton',
  'Duran Duran',
  'Russell Morris',
  'Hanson',
  'Foo Fighters',
  'Wham!',
  'Amy Winehouse',
  'Lenny Kravitz',
  'The Who',
  'The Verve',
  'Silverchair',
  'Alanis Morissette',
  'Michael Jackson',
  'Ed Sheeran',
  'Neil Diamond',
  'Dire Straits',
  'Blur',
  'Split Enz',
  'George Michael, Aretha Franklin',
  'John Lennon',
  'a-ha',
  'Lou Reed',
  'Van Morrison',
  'The Rolling Stones',
  'Paul Kelly',
  'Midnight Oil',
  'Elton John',
  'U2',
  'ABBA',
  'Cold Chisel',
  'Daryl Braithwaite',
  'OutKast',
  'Elvis Presley',
  'Faith No More',
  'Beyoncé, JAY Z',
  'AC/DC',
  'Madonna',
  'Crowded House',
  'Fleetwood Mac',
  'Natalie Imbruglia',
  'David Bowie',
  'Alanis Morissette',
  'The Who',
  'The Doors',
  'Bon Jovi',
  'Marvin Gaye',
  'KISS',
  'Kenny Loggins',
  'Stevie Wright',
  'Backstreet Boys',
  'The Avalanches',
  'Nirvana',
  'The Police',
  'Cyndi Lauper',
  'Crowded House',
  'The Saints',
  'Kings of Leon',
  'Michael Jackson',
  'James Brown',
  'R.E.M.',
  'AC/DC',
  'Living Colour',
  'Pat Benatar',
  'Alicia Keys',
  'George Michael, Elton John',
  'INXS',
  'The Kinks',
  'Queen',
  'TLC',
  'The Rolling Stones',
  'Joni Mitchell',
  'The Church',
  'Divinyls',
  'Joan Jett & The Blackhearts',
  'Roy Orbison',
  'Nick Cave & The Bad Seeds, Kylie Minogue',
  'Bee Gees',
  'Prince',
  'Deee-Lite',
  "Guns N' Roses",
  'Cold Chisel',
  'Queen',
  'Simple Minds',
  'Led Zeppelin',
  'U2',
  'Michael Jackson',
  'Alicia Bridges',
  'Earth, Wind & Fire, The Emotions',
  'Australian Crawl',
  'Johnny Cash',
  'Elton John',
  'George Michael',
  'Bill Medley, Jennifer Warnes',
  'Creedence Clearwater Revisited',
  'Culture Club',
  'AC/DC',
  'Bryan Adams',
  'Skyhooks',
  'Metallica',
  'Pretenders',
  'Hot Chocolate',
  'Jimmy Barnes',
  'Extreme',
  'Blondie',
  'ABBA',
  'Bob Dylan',
  'Red Hot Chili Peppers',
  'David Bowie',
  'Tracy Chapman',
  'The Who',
  'Ben Folds Five',
  'k.d. lang',
  'Radiohead',
  'The Cranberries',
  'Dusty Springfield',
  'Village People',
  'Madonna',
  'Oasis',
  'Soft Cell',
  'Split Enz',
  'U2',
  'The Supremes',
  'Adele',
  'Pearl Jam',
  'The Wailers',
  'R.E.M.',
  'Meat Loaf',
  'George Michael',
  'Nick Cave & The Bad Seeds',
  'The Beach Boys',
  'The Monkees',
  'The Clash',
  'John Travolta, Olivia Newton-John',
  'Eurythmics',
  'Aerosmith',
  'Elvis Costello & The Attractions',
  'Martika',
  'The Black Eyed Peas',
  'Cold Chisel',
  'Lynyrd Skynyrd',
  'Bon Jovi',
  'Tina Arena',
  'Bruce Springsteen',
  'OneRepublic',
  'The Rolling Stones',
  'Europe',
  'Michael Jackson',
  'Tears For Fears',
  'David Bowie',
  'INXS',
  'Kanye West, Jamie Foxx',
  'Irene Cara',
  'Queen',
  'Chris Isaak',
  'Kelis',
  'Midnight Oil',
  'Phil Collins',
  'Paul Kelly',
  'Leo Sayer',
  'Run–D.M.C.',
  'The Killers',
  'Sheryl Crow',
  'THE STAFF BAND OF THE NORWEGIAN ARMED FORCES',
  'Elton John',
  'The Smashing Pumpkins',
  'Duran Duran, David Kershenbaum',
  'ABBA',
  'Hunters & Collectors',
  'The Moody Blues',
  'Van Halen',
  'Counting Crows',
  'AC/DC',
  'INXS',
  'Pseudo Echo',
  'Red Hot Chili Peppers',
  'Iggy Pop',
  'Prince',
  'Madonna',
  'Janet Jackson',
  'Robbie Williams, Kylie Minogue',
  'The Jackson 5',
  'Eurythmics',
  'Ed Sheeran',
  'Salt-N-Pepa, En Vogue',
  'Jimi Hendrix',
  'Lionel Richie',
  'Missy Higgins',
  'U2',
  'Starship',
  'Chaka Khan',
  'Rihanna, JAY Z',
  'Crowded House',
  'Robert Palmer, UB40',
  'Ultravox',
  'Paul McCartney, Wings',
  'Matchbox Twenty',
  'The Pointer Sisters',
  'Talking Heads',
  'Tina Turner',
  'Fatboy Slim',
  'Meat Loaf',
  'INXS',
  'The Bangles',
  'ICEHOUSE',
  'The Cure',
  'Kylie Minogue',
  'Queen',
  'Fleetwood Mac',
  'Bruce Springsteen',
  'GANGgajang',
  'Radiohead',
  'U2',
  'Michael Jackson',
  'Frank Sinatra',
  'New Order',
  'Coldplay',
  'George Harrison',
  'Berlin',
  'Aerosmith',
  'Toni Basil',
  'Massive Attack',
  'Paul Kelly',
  'The Goo Goo Dolls',
  'Bryan Ferry',
  'Don Henley',
  'Björk',
  'John Mellencamp',
  'Ike & Tina Turner',
  'Bruce Springsteen',
  'Taylor Swift',
  'Rod Stewart',
  'Pearl Jam',
  'AC/DC',
  'Queen, David Bowie',
  'Dixie Chicks',
  'New Order',
  'Amii Stewart',
  'Madonna',
  'Cold Chisel',
  'Marvin Gaye',
  'N.W.A.',
  'Justin Timberlake',
  'Blondie',
  'Salt-N-Pepa',
  'Maroon 5',
  "Guns N' Roses",
  'Santana, Rob Thomas',
  'Nelly Furtado',
  'Bananarama',
  'Tom Petty and the Heartbreakers',
  'Madness',
  'Eminem',
  'U2',
  'Sade',
  'Black Sabbath',
  'Crowded House',
  'Faith No More',
  'Sunnyboys',
  'Nickelback',
  'Cutting Crew',
  'Stevie Wonder',
  'Madonna',
  'Various Artists, Pharrell Williams',
  'Lisa Loeb & Nine Stories',
  'Louis Armstrong',
  "The B-52's",
  'Violent Femmes',
  'Silverchair',
  'The Angels',
  'Maxi Priest',
  'Tom Petty',
  'Prince',
  'KC & The Sunshine Band',
  'Janet Jackson',
  'The Cruel Sea',
  'Spandau Ballet',
  'Cold Chisel',
  'Whitesnake',
  'George Michael',
  'U2',
  'Everclear',
  'The Jackson 5',
  'Tom Cochrane',
  'Poison',
  'Crowded House',
  'Rick Springfield',
  'Creed',
  "Guns N' Roses",
  'Tone-Loc',
  'Little River Band',
  'Roxy Music',
  'The Stone Roses',
  'The Animals',
  'Def Leppard',
  'Bruce Springsteen',
  'Frank Sinatra, Tony Bennett',
  'Prince',
  'Alannah Myles',
  'David Bowie',
  'Massive Attack',
  'Beastie Boys',
  'Aaliyah',
  'Fleetwood Mac',
  'Cheap Trick',
  'Bachman-Turner Overdrive',
  'Tina Turner',
  'Stevie Wonder',
  'Bob Marley & The Wailers',
  'Fine Young Cannibals',
  'Pulp',
  'Michael Jackson',
  'Cold Chisel',
  'A Flock Of Seagulls',
  'De La Soul',
  'The Rolling Stones',
  'TOTO',
  'Beats International',
  'Divinyls',
  'Jason Mraz',
  'ICEHOUSE',
  'Arrested Development',
  'R.E.M.',
  'THE SPORTS',
  'U2, B.B. King',
  'The Doors',
  'Grandmaster Flash & The Furious Five',
  'Genesis',
  'Sir Mix-A-Lot',
  'Meat Loaf',
  'George Thorogood & The Destroyers',
  'Van Halen',
  'David Bowie',
  'Oasis',
  'John Farnham',
  'Sex Pistols',
  'Prince',
  'Melissa Etheridge',
  'Pink Floyd',
  'Elvis Presley',
  'Nena',
  'Michael Jackson',
  'TOTO',
  'Big Audio Dynamite',
  'U2',
  'Ramones',
  'The Stranglers',
  'Dusty Springfield',
  'Queen',
  'Alicia Keys',
  'Midnight Oil',
  'David Bowie',
  'Eurythmics',
  'Bob Dylan',
  'Cold Chisel',
  'Mariah Carey',
  'Chaka Khan',
  'Iggy Pop',
  'UB40',
  'Kate Bush',
  'Mumford & Sons',
  'Bryan Adams',
  'Sting',
  'The Rolling Stones',
  'Wild Cherry',
  'You Am I',
  'Womack & Womack',
  'Natalie Cole, Nat King Cole',
  'The Jam',
  'John Lennon',
  'John Paul Young',
  'Bonnie Tyler',
  'TLC',
  'John Mellencamp',
  'Bruce Springsteen',
  'Wet Wet Wet',
  'The Doors',
  'Pearl Jam',
  'Split Enz',
  'Pink Floyd',
  'George Michael',
  'Talking Heads',
  'Propellerheads',
  'Prince',
  'Village People',
  'Bon Jovi',
  'Depeche Mode',
  'AC/DC',
  'Dido',
  'John Farnham',
  'The Rolling Stones',
  'David Bowie',
  'Regurgitator',
  'Carpenters',
  'Steve Winwood',
  'Fatboy Slim, Bootsy Collins',
  'Blondie',
  'Redgum',
  'U2',
  'Simon & Garfunkel',
  'Divinyls',
  'Eric Clapton',
  'David Bowie',
  'Paul Lekakis',
  'Kelly Clarkson',
  'The Prodigy',
  'The Cars',
  'Powderfinger',
  'John Travolta, Olivia Newton-John',
  'Crowded House',
  'MGMT',
  'Paula Abdul',
  'Motörhead',
  'Queen',
  'The Human League',
  'Ike & Tina Turner',
  '*NSYNC',
  'Wendy Matthews',
  'Sherbet',
  'The Proclaimers',
  'Fiona Apple',
  'Frankie Goes To Hollywood',
  'Killing Heidi',
  'Bee Gees',
  'The Cure',
  'Linkin Park',
  'Murray Head',
  'Joe Cocker',
  'Duran Duran',
  'Kate Bush',
  "Terence Trent D'Arby",
  'Queen',
  'The Dream Academy',
  'Bob Marley & The Wailers',
  'Eurythmics',
  'Lionel Richie',
  'Gorillaz',
  'Kim Carnes',
  'Led Zeppelin',
  'DEVO',
  'John Lennon, The Plastic Ono Band, The Flux Fiddlers',
  'Mariah Carey',
  'The Dandy Warhols',
  'Concrete Blonde',
  'Bob Dylan',
  'Sophie B. Hawkins',
  'Goanna',
  'The Righteous Brothers',
  'Divinyls',
  'Jewel',
  'Robert Palmer',
  'Jimi Hendrix',
  'Foo Fighters',
  'The Clash',
  'The Buggles',
  'John Lennon',
  'Simply Red',
  "Jane's Addiction",
  'The Church',
  'Boyz II Men',
  'Third Eye Blind',
  'The Rolling Stones',
  'Beastie Boys',
  'John Denver',
  'Elton John',
  'Sonia Dada',
  'The Cure',
  'Martika',
  'Skyhooks',
  'Pat Benatar',
  'Midnight Oil',
  'Craig David',
  'Macy Gray',
  'Mötley Crüe',
  'Roy Orbison',
  'Tone-Loc',
  'Foreigner',
  'The Commitments, Andrew Strong',
  'Adele',
  'Queen',
  'Eagles',
  'Daft Punk',
  'ABBA',
  'Choirboys',
  'The Doors',
  'MC Hammer',
  'Charles & Eddie',
  'Twisted Sister',
  'Cyndi Lauper',
  'Paul McCartney, Wings',
  'Traveling Wilburys',
  'Bruce Springsteen',
  'Spice Girls',
  'Evanescence',
  'The Bangles',
  'Percy Sledge',
  'Oasis',
  'Ed Sheeran',
  'INXS',
  'Rod Stewart',
  'All Saints, Unknown',
  'Michael Jackson',
  'Fleetwood Mac',
  'Australian Crawl',
  'Powderfinger',
  'Adam & The Ants',
  'Pet Shop Boys',
  'Pink Floyd',
  'Sister Sledge',
  'The Black Eyed Peas',
  'Tears For Fears',
  'Steppenwolf',
  'Madonna',
  "The Go-Go's",
  'Dragon',
  'Dexys Midnight Runners',
  '2Pac, Roger, Dr. Dre',
  'AC/DC',
  'Kim Wilde',
  'Shania Twain',
  'Live',
  'Billy Joel',
  'Beck',
  'ABBA',
  'The Style Council',
  'Snow Patrol',
  'Seals and Crofts',
  'Sia',
  "Guns N' Roses",
  'Tracy Chapman',
  'Billy Thorpe & The Aztecs',
  'Mötley Crüe',
  'Gnarls Barkley',
  'George Michael',
  'ZZ Top',
  'Savage Garden',
  'Whitney Houston',
  'Bruno Mars',
  'Frankie Valli & The Four Seasons',
  'Jimmy Cliff',
  'Steve Winwood',
  'The Cruel Sea',
  'P!nk',
  'The Jacksons',
  'Crash Test Dummies',
  'Roxette',
  'No Doubt',
  'Talking Heads',
  'Janet Jackson',
  'U2',
  'Nirvana',
  'Pretenders',
  'New Kids On The Block',
  'Midnight Oil',
  'Elvis Presley',
  'INXS',
  'The Police',
  'Hilltop Hoods',
  'The J. Geils Band',
  'America',
  'Eagle-Eye Cherry',
  'U.S.A. For Africa',
  'P!nk',
  'Foreigner',
  'Lorde',
  'The Cars',
  'Blur',
  "Youssou N'Dour, Neneh Cherry",
  'Electric Light Orchestra',
  'Texas',
  'Blind Melon',
  'Justin Timberlake, Timbaland',
  'The Smiths',
  'Suzanne Vega, DNA',
  'Cheap Trick',
  'Adele',
  'The Romantics',
  'The Whitlams',
  'The Waterboys',
  'Matchbox Twenty',
  'Led Zeppelin',
  'Queen',
  'Wilson Phillips',
  'The Lemonheads',
  'Neil Diamond',
  'Survivor',
  'Diesel',
  'C & C Music Factory',
  'Coldplay',
  'Seal',
  'Steve Miller Band',
  'Dire Straits',
  'Brandy, Monica',
  'Robbie Williams',
  'R.E.M.',
  'Dolly Parton',
  'Ace of Base',
  'Midnight Oil',
  'Kylie Minogue',
  'Eagles',
  'Baby Animals',
  'Wham!',
  'Right Said Fred',
  'The Strokes',
  'Elton John, Kiki Dee',
  'Aerosmith',
  'The Screaming Jets',
  'Dragon',
  'Stars On 54',
  'The Temptations',
  'David Gray',
  'John Travolta, Jeff Conaway',
  'Cold Chisel',
  'Frankie Goes To Hollywood',
  'Heart',
  'Kings of Leon',
  'Diana King',
  'Mike & The Mechanics',
  'New Radicals',
  'Joe Cocker',
  'Scissor Sisters',
  'Enya',
  'Justin Timberlake',
  'Lenny Kravitz',
  'The Go-Betweens',
  'Van Morrison',
  'World Party, Anthony Thistlethwaite',
  'Katy Perry',
  'Foreigner',
  'Gwen Stefani',
  'M',
  'The Motels',
  'Robbie Williams',
  'blink-182',
  'Pretenders',
  'Billy Joel',
  'Ben E. King',
  'Talking Heads',
  'Lupe Fiasco, Guy Sebastian',
  'Kenny Rogers, Dolly Parton',
  'Hanson',
  '10cc',
  'Real Life',
  'Jon Bon Jovi',
  'Gary Numan',
  'Blackstreet, Dr. Dre, Queen Pen',
  'Peter Cetera',
  'John Butler Trio',
  'The Boomtown Rats',
  'Roxette',
  'Joe Cocker',
  'Lady Antebellum',
  'Tori Amos, Armand Van Helden',
  'Simon & Garfunkel',
  'Diddy, Faith Evans, 112',
  'David Bowie, Mick Jagger',
  'Gin Blossoms',
  'Yes',
  'Everything But The Girl',
  'Garbage',
  'Vanilla Ice',
  'George Harrison',
  'The Black Keys',
  'Bryan Adams',
  '50 Cent',
  'Fleetwood Mac',
  'INXS',
  'Rihanna',
  'Soundgarden',
  'Depeche Mode',
  'Christina Aguilera',
  'Paul Kelly',
  'Gabrielle Aplin, Bastille',
  'Rob Thomas',
  'Earth, Wind & Fire',
  'ABBA',
  'Young MC',
  'Kool & The Gang',
  'Bernard Fanning',
  'The Cure',
  'The Offspring',
  'Belinda Carlisle',
  'The Rembrandts',
  'The Cult',
  'Jennifer Lopez',
  "Robert Palmer, Eric 'ET' Thorngren",
  'Train',
  'Donna Summer',
  'Naughty By Nature',
  'Huey Lewis & The News',
  'Metallica',
  'Crystal Waters',
  'Transvision Vamp',
  'Limp Bizkit',
  "The Lovin' Spoonful",
  'Savage Garden',
  'Rihanna, Kanye West, Paul McCartney',
  'Eric Carmen',
  'Missy Elliott',
  'Steve Miller Band',
  'Laura Branigan',
  'The Escape Club',
  'Rage Against The Machine',
  "Terence Trent D'Arby",
  'Urge Overkill',
  'Pretenders',
  'Eric Prydz',
  'Red Hot Chili Peppers',
  'Iron Maiden',
  'Kylie Minogue',
  'David Lee Roth',
  'The Mamas & The Papas',
  'Bryan Ferry',
  'The Rolling Stones',
  '',
  'Underworld',
  'Fergie',
  'Billy Idol',
  'Yusuf / Cat Stevens',
  'Tom Petty and the Heartbreakers',
  'The Killers',
  'Traveling Wilburys',
  "Guns N' Roses",
  'ABC',
  'Jamiroquai',
  'The Chemical Brothers',
  'Arctic Monkeys',
  'Hootie & The Blowfish',
  'Cypress Hill',
  'U2',
  'Glenn Frey',
  'Audioslave',
  'Mariah Carey',
  'Michael Jackson',
  'The Soup Dragons, Junior Reid',
  'Bee Gees',
  'The Presets',
  'Thirty Seconds To Mars',
  'Billy Ocean',
  'Foo Fighters',
  'Diana Ross',
  'Faith Hill',
  'Gerry Rafferty',
  'Tenacious D',
  'Julian Lennon',
  'Rose Tattoo',
  'Lady Gaga',
  'Oasis',
  'Kenny Loggins',
  'Birds Of Tokyo',
  'Kelly Clarkson',
  'Warren Zevon',
  'Nine Inch Nails',
  'Dave Dobbyn, Herbs',
  'R. Kelly',
  'Inner Circle',
  'Stevie Nicks',
  'James Blunt',
  'Axiom',
  'Phil Oakey, Giorgio Moroder',
  'Earth, Wind & Fire',
  'Backstreet Boys',
  'Public Enemy',
  'Bob Marley & The Wailers',
  'Jimi Hendrix',
  'CeeLo Green',
  'Franz Ferdinand',
  'ABBA',
  'George Michael',
  'Orchestral Manoeuvres In The Dark',
  'Chris Isaak',
  'Prince',
  'Coldplay',
  'Alice Cooper',
  'Gino Vannelli',
  'Men At Work',
  'Green Day',
  'Small Faces',
  'P!nk',
  'Phil Collins',
  'The Smashing Pumpkins',
  'Patti Smith',
  'Bon Jovi',
  'CHIC',
  'Christine Anu',
  'The Sugarhill Gang',
  'Jet',
  'EMF',
  'Exile',
  'The Communards, Sarah Jane Morris',
  '4 Non Blondes',
  'George Benson',
  'Bruno Mars',
  'The Offspring',
  'Bobby McFerrin',
  'LeAnn Rimes',
  'Coolio, L.V.',
  'AC/DC',
  'Robbie Williams',
  'Billy Idol',
  'Jimmy Barnes',
  'John Lennon, Jon Anderson, Chris Squire, Paul McCartney, Robert Downey Jr.',
  'John Mayer',
  'Peter Gabriel',
  'Soul II Soul, Caron Wheeler',
  'Vic Reeves, The Wonder Stuff',
  'Fairground Attraction',
  'Foo Fighters',
  'DJ Jazzy Jeff & The Fresh Prince',
  'Royal Philharmonic Orchestra',
  'Alex Lloyd',
  'M People',
  'Bronski Beat',
  'Bill Withers',
  'Boom Crash Opera',
  'Ginuwine',
  "The B-52's",
  'The Darkness',
  'Bush',
  'Elton John',
  'Eagles',
  'Spin Doctors',
  'The Beach Boys',
  'Kylie Minogue',
  'Steve Earle',
  'Led Zeppelin',
  'Seal',
  'Pretenders',
  'Vance Joy',
  'Paul McCartney, Wings',
  'Dead Or Alive',
  'Robbie Williams',
  'Moving Pictures',
  'Fuel',
  'Rod Stewart',
  'TLC',
  'Cher',
  'Spiderbait',
  'Neil Young',
  'No Doubt',
  'Australian Crawl',
  'Yusuf / Cat Stevens',
  'Christina Aguilera',
  'Joan Armatrading',
  'Elvis Presley',
  'INXS',
  'Red Hot Chili Peppers',
  'Paul Young',
  'The Temper Trap',
  'Bob Marley & The Wailers',
  'Cream',
  'Billy Joel',
  'The Living End',
  'Creedence Clearwater Revival',
  'Foo Fighters',
  'Mystique',
  'Bonnie Raitt',
  'Eagles',
  'Green Day',
  'REO Speedwagon',
  'Eminem, Dido',
  'The Angels',
  'Crowded House',
  'Passenger',
  'Van Halen',
  'Incubus',
  'The Specials, Rico',
  'George Michael',
  'Jimi Hendrix',
  'KISS',
  'Fatboy Slim',
  'Sting',
  'The White Stripes',
  'Hole',
  'INXS',
  'Ike & Tina Turner',
  "Destiny's Child",
  'ICEHOUSE',
  'John Legend',
  'The Badloves, Jimmy Barnes',
  'Elton John',
  'Joe Jackson',
  'John Lennon, The Plastic Ono Band, Yoko Ono',
  'Kasey Chambers',
  'Van Morrison',
  'Sam Smith',
  'Patti LaBelle',
  'The Black Crowes',
  'Kenny Rogers',
  'Los Lobos',
  'Nelly',
  'The Smashing Pumpkins',
  'The Doobie Brothers',
  'Marc Cohn',
  'The Commitments',
  'Macklemore & Ryan Lewis, Mary Lambert',
  'Sweet',
  'Grinspoon',
  'Weezer',
  'Tom Petty',
  'Sonny & Cher',
  'Daryl Hall & John Oates',
  'Ben Lee',
  'Soul Asylum',
  'Rick James',
  'Jackson Browne',
  'The Police',
  'Ms. Lauryn Hill',
  'Thin Lizzy',
  'U2',
  'Bohemian Rhapsody ',
  "Sweet Child O' Mine",
  'Smells Like Teen Spirit',
  'Imagine ',
  "You're the Voice",
  'Stairway to Heaven ',
  'Purple Rain',
  "It's a Long Way to the Top (If You Wanna Rock 'N' Roll)",
  'Thriller ',
  "(I Can't Get No) Satisfaction ",
  'Dancing Queen',
  "Livin' On A Prayer",
  'Friday on My Mind',
  'Like a Virgin',
  'Good Vibrations ',
  "Knockin' On Heaven's Door ",
  'Hotel California ',
  'Careless Whisper',
  "I Still Haven't Found What I'm Looking For ",
  'Respect',
  'I Will Always Love You',
  'Somebody That I Used To Know',
  'Smoke On The Water ',
  'Better Be Home Soon',
  'Light My Fire ',
  'Down Under',
  'Wonderwall ',
  "What's Going On",
  'Khe Sanh',
  "Stayin' Alive ",
  'Single Ladies (Put a Ring on It)',
  'Wannabe',
  'Superstition',
  "Can't Get You out of My Head",
  'Under the Bridge',
  'You Took The Words Right Out of My Mouth (Hot Summer Night)',
  'Karma Chameleon',
  'Angels',
  'Rhiannon',
  'Enter Sandman',
  "Don't Be Cruel",
  'Need You Tonight',
  'Space Oddity ',
  'Last Goodbye',
  'Girls Just Want to Have Fun',
  'Another Brick in the Wall, Pt. 2',
  'Treaty (Radio Mix)',
  'American Pie',
  'Nothing Compares 2 U',
  "You're so Vain",
  'All Along the Watchtower',
  'Good Riddance (Time of Your Life)',
  'Call Me',
  'Uptown Funk',
  'Blame It on the Boogie',
  'You Can Call Me Al',
  'Throw Your Arms Around Me',
  'Piano Man',
  'Working Class Man',
  'The Real Slim Shady',
  'Love Will Tear Us Apart',
  'Truly Madly Deeply',
  'In The Air Tonight ',
  'Oops!...I Did It Again',
  'My Sharona',
  'Losing My Religion',
  'Tiny Dancer',
  'Born in the U.S.A.',
  "Let's Talk About Sex",
  'Eagle Rock ',
  'My Happiness',
  'Hey Jude',
  'Alive',
  'Rolling in the Deep',
  'Beds Are Burning ',
  'Creep',
  'London Calling ',
  'Back for Good ',
  'Great Southern Land',
  'Clocks',
  'I Will Survive ',
  'Killing Me Softly With His Song',
  'Every Breath You Take ',
  'Tears in Heaven ',
  'Girls on Film ',
  'The Real Thing',
  'MMMBop',
  'Everlong',
  'Wake Me up Before You Go',
  'Rehab',
  'Are You Gonna Go My Way',
  'My Generation ',
  'Bitter Sweet Symphony',
  'Straight Lines',
  'You Oughta Know',
  'Billie Jean',
  'Thinking out Loud',
  'Sweet Caroline',
  'Money For Nothing',
  'Song 2',
  'Message To My Girl',
  'I Knew You Were Waiting (For Me)',
  'Stand By Me ',
  'Take on Me',
  'Walk On the Wild Side',
  'Gloria',
  'Angie ',
  'Dumb Things',
  'Blue Sky Mine ',
  'Candle In The Wind ',
  'With Or Without You ',
  'Mamma Mia',
  'Cheap Wine ',
  'The Horses ',
  'Hey Ya!',
  'In the Ghetto',
  'Epic',
  'Crazy In Love (feat. Jay',
  'Thunderstruck',
  'Holiday',
  'Weather With You',
  'Dreams ',
  'Torn',
  'Changes ',
  'Ironic ',
  'You Better You Bet',
  'L.A. Woman',
  'You Give Love A Bad Name',
  'I Heard It Through The Grapevine',
  "I Was Made For Lovin' You",
  'Footloose ',
  'Evie Pt. 1 (Let Your Hair Hang Down)',
  "Everybody (Backstreet's Back) ",
  'Since I Left You',
  'Come As You Are',
  'Roxanne ',
  'True Colors',
  'Fall At Your Feet',
  "(I'm) Stranded",
  'Sex on Fire',
  'Beat It ',
  'I Got You (I Feel Good)',
  'Everybody Hurts',
  'You Shook Me All Night Long',
  'Love Rears Its Ugly Head',
  'Love Is A Battlefield ',
  'Empire State of Mind (Part II) Broken Down',
  "Don't Let the Sun Go Down on Me",
  'Original Sin',
  'Lola ',
  'Another One Bites The Dust ',
  'No Scrubs',
  'Miss You ',
  'Big Yellow Taxi',
  'The Unguarded Moment ',
  'I Touch Myself',
  "I Love Rock n' Roll",
  'You Got It',
  'Where the Wild Roses Grow ',
  'How Deep Is Your Love',
  'Kiss',
  'Groove Is in the Heart',
  'Paradise City',
  'When The War Is Over',
  'We Will Rock You ',
  "Don't You (Forget About Me) ",
  'Whole Lotta Love ',
  'Mysterious Ways',
  'Man in the Mirror',
  'I Love The Nightlife',
  'Boogie Wonderland',
  'The Boys Light Up ',
  'Hurt',
  'Bennie And The Jets ',
  'Too Funky ',
  "(I've Had) The Time of My Life",
  'Looking Out My Backdoor (Live)',
  'Do You Really Want To Hurt Me',
  'Dirty Deeds Done Dirt Cheap',
  '(Everything I Do) I Do It For You',
  'Ego Is Not A Dirty Word ',
  'Nothing Else Matters',
  'Brass in Pocket',
  "Every 1's a Winner",
  'Good Times',
  'More Than Words',
  'The Tide Is High',
  'Gimme! Gimme! Gimme! (A Man After Midnight)',
  'Hurricane',
  'By the Way',
  'China Girl ',
  'Give Me One Reason',
  'Who Are You',
  'Brick',
  'Constant Craving',
  'High And Dry',
  'Zombie',
  'Son Of A Preacher Man',
  'YMCA ',
  "Papa Don't Preach",
  'Morning Glory ',
  'Tainted Love',
  'I See Red',
  'Where The Streets Have No Name ',
  'Baby Love ',
  'Set Fire to the Rain',
  'Even Flow',
  'I Shot The Sheriff',
  "It's The End Of The World As We Know It (And I Feel Fine)",
  "I'd Do Anything For Love (But I Won't Do That) ",
  'I Want Your Sex ',
  'The Ship Song ',
  'Kokomo',
  'Daydream Believer',
  'Should I Stay or Should I Go ',
  'Summer Nights ',
  "Sisters Are Doin' It for Themselves ",
  "I Don't Want to Miss a Thing ",
  "Oliver's Army",
  'Toy Soldiers',
  'I Gotta Feeling',
  'Saturday Night',
  'Sweet Home Alabama',
  'Bad Medicine',
  'Chains',
  'Glory Days',
  'Apologize',
  "Jumpin' Jack Flash",
  'The Final Countdown',
  'Black or White ',
  'Shout',
  'Ashes to Ashes',
  'What You Need',
  'Gold Digger',
  'Flashdance...What a Feeling ',
  'Killer Queen ',
  'Wicked Game',
  'Milkshake',
  'King Of The Mountain ',
  'A Groovy Kind of Love ',
  'Before Too Long',
  'You Make Me Feel Like Dancing ',
  'Walk This Way',
  'Somebody Told Me',
  'All I Wanna Do',
  'Sledgehammer (Peter Gabriel/Jarle G. Storløkken)',
  'Your Song',
  '1979 ',
  'Rio ',
  'Take A Chance On Me',
  'Holy Grail',
  'Nights In White Satin ',
  'Jump ',
  'Mr. Jones',
  'Who Made Who',
  'Devil Inside',
  'Funky Town',
  'Give It Away',
  'Lust For Life',
  '1999',
  'Like a Prayer',
  "That's The Way Love Goes",
  'Kids',
  'I Want You Back',
  "Who's That Girl ",
  'Lego House',
  'Whatta Man',
  'Purple Haze',
  'Dancing On The Ceiling',
  'Scar',
  'Sweetest Thing ',
  'We Built This City',
  "Ain't Nobody",
  'Umbrella',
  'Something So Strong',
  "I'll Be Your Baby Tonight (feat. UB40)",
  'Vienna',
  'The Long And Winding Road ',
  'Push',
  "I'm So Excited",
  'Burning Down the House',
  'The Best',
  'Praise You',
  'Bat Out Of Hell ',
  'Never Tear Us Apart',
  'Manic Monday',
  'Electric Blue',
  'Close To Me',
  'Confide in Me ',
  'I Want To Break Free ',
  "Don't Stop ",
  'Hungry Heart',
  'Sounds of Then (This Is Australia)',
  'Karma Police',
  'All I Want Is You',
  'Bad ',
  'My Way',
  'Blue Monday',
  'Yellow',
  'My Sweet Lord',
  'Take My Breath Away',
  "Janie's Got A Gun ",
  'Mickey',
  'Teardrop',
  'To Her Door',
  'Iris',
  "Let's Stick Together",
  'The Boys Of Summer',
  "It's Oh So Quiet",
  'Jack & Diane',
  'Nutbush City Limits',
  'Dancing In the Dark',
  'Love Story',
  "Da Ya Think I'm Sexy?",
  'Jeremy',
  'Back In Black',
  'Under Pressure ',
  'Not Ready to Make Nice',
  'Bizarre Love Triangle',
  'Knock On Wood',
  'Vogue',
  'Flame Trees',
  'Sexual Healing',
  'Express Yourself',
  'Cry Me a River',
  'Heart Of Glass ',
  'Push It',
  'This Love',
  'Welcome To The Jungle',
  'Smooth (feat. Rob Thomas)',
  "I'm Like A Bird",
  'Venus',
  'Learning To Fly',
  'It Must Be Love',
  'Lose Yourself ',
  'Sunday Bloody Sunday ',
  'Smooth Operator ',
  'Paranoid',
  "Don't Dream It's Over",
  'Easy',
  'Alone with You ',
  'How You Remind Me',
  '(I Just) Died In Your Arms',
  "Signed, Sealed, Delivered (I'm Yours)",
  'Material Girl',
  'Happy',
  'Stay',
  'What A Wonderful World',
  'Love Shack',
  'Blister in the Sun ',
  'Tomorrow',
  'Am I Ever Gonna See Your Face Again (live)',
  'Close To You',
  "I Won't Back Down",
  "Let's Go Crazy",
  "That's the Way (I Like It) ",
  'Escapade',
  'The Honeymoon Is Over',
  'TRUE ',
  'Bow River',
  'Here I Go Again ',
  "Freedom! '90",
  'Beautiful Day',
  'Santa Monica',
  'ABC',
  'Life Is A Highway',
  'Every Rose Has Its Thorn ',
  'Distant Sun',
  "Jessie's Girl",
  'With Arms Wide Open ',
  'November Rain',
  'Wild Thing',
  'Help Is On Its Way ',
  'Avalon ',
  'Fools Gold ',
  'The House of the Rising Sun',
  'Pour Some Sugar On Me (2012)',
  'Born to Run',
  'New York, New York',
  'When Doves Cry',
  'Black Velvet',
  'Heroes ',
  'Unfinished Sympathy',
  'Fight For Your Right',
  'Try Again',
  'Tusk',
  'If You Want My Love',
  "You Ain't Seen Nothing Yet",
  "What's Love Got to Do with It",
  'Living For The City',
  'Buffalo Soldier',
  'She Drives Me Crazy',
  'Common People',
  'The Way You Make Me Feel',
  'Choirgirl',
  'I Ran',
  'Me, Myself & I',
  'Brown Sugar',
  'Africa',
  'Dub Be Good To Me',
  'Boys In Town',
  "I'm Yours",
  'We Can Get Together',
  'People Everyday',
  'Orange Crush',
  'Who Listens to the Radio',
  'When Love Comes To Town',
  'Roadhouse Blues',
  'The Message',
  'Invisible Touch ',
  'Baby Got Back',
  "Two Out of Three Ain't Bad",
  'Bad To The Bone',
  'Dreams',
  'Ziggy Stardust ',
  'Champagne Supernova ',
  'Age of Reason',
  'Anarchy In The UK',
  'Cream ',
  'Similar Features',
  'Comfortably Numb',
  'Suspicious Minds',
  '99 Luftballons',
  "Don't Stop 'Til You Get Enough ",
  'Rosanna',
  'The Globe',
  "New Year's Day",
  'I Wanna Be Sedated ',
  'Golden Brown',
  "I Just Don't Know What To Do With Myself",
  'Crazy Little Thing Called Love ',
  "Fallin'",
  'Power And The Passion ',
  'Fame ',
  'Here Comes the Rain Again ',
  'Subterranean Homesick Blues',
  'Forever Now',
  'Emotions',
  "I'm Every Woman",
  'Real Wild Child (Wild One)',
  'Red Red Wine',
  'Babooshka',
  'Little Lion Man',
  "Summer Of '69",
  'Russians',
  'Emotional Rescue ',
  'Play That Funky Music',
  'Berlin Chair',
  'Teardrops',
  'Unforgettable',
  'Town Called Malice',
  'Woman',
  'Love Is in the Air',
  'Total Eclipse of the Heart',
  'Waterfalls',
  'Hurts So Good',
  'Streets of Philadelphia ',
  'Love Is All Around ',
  'Break on Through (To the Other Side)',
  'Better Man ',
  'I Got You',
  'Wish You Were Here',
  'Faith ',
  'And She Was ',
  'History Repeating (Featuring Miss Shirley Bassey)',
  'Little Red Corvette ',
  'Macho Man',
  'Wanted Dead Or Alive',
  'Personal Jesus',
  'Highway to Hell',
  'Thank You',
  'Pressure Down',
  "You Can't Always Get What You Want",
  "Let's Dance ",
  'Polyester Girl',
  'Top Of The World',
  'While You See A Chance',
  'Weapon Of Choice (feat. Bootsy Collins) ',
  'Rapture',
  'I Was Only 19 (A Walk in the Light Green)',
  'One',
  'Bridge Over Troubled Water',
  'Pleasure And Pain',
  'Layla ',
  'Golden Years ',
  'Boom, Boom (Let’s Go Back To My Room) (Re',
  'Miss Independent',
  'Breathe',
  'Drive',
  'Pick You Up',
  "You're The One That I Want ",
  "It's Only Natural",
  'Kids',
  'Opposites Attract',
  'Ace of Spades',
  'Somebody To Love ',
  "Don't You Want Me ",
  'Shake a Tail Feather',
  'Bye Bye Bye',
  'The Day You Went Away ',
  'Howzat',
  "I'm Gonna Be (500 Miles)",
  'Criminal',
  'Relax',
  'Weir',
  'Night Fever',
  'The Lovecats',
  'In the End',
  'One Night In Bangkok ',
  'With A Little Help From My Friends',
  'Hungry Like the Wolf ',
  'Wuthering Heights',
  'Wishing Well',
  'We Are The Champions ',
  'Life in a Northern Town',
  'One Love / People Get Ready',
  'Sweet Dreams (Are Made of This) ',
  'Hello',
  'Feel Good Inc.',
  'Bette Davis Eyes',
  'Kashmir ',
  'Whip It',
  'Jealous Guy ',
  'Hero',
  'Bohemian Like You',
  'Joey',
  'Like a Rolling Stone',
  'Damn I Wish I Was Your Lover',
  'Solid Rock ',
  'Unchained Melody ',
  'Science Fiction',
  'Who Will Save Your Soul',
  'Simply Irresistible',
  'Voodoo Chile',
  'Best of You',
  'Rock the Casbah ',
  'Video Killed The Radio Star',
  'Beautiful Boy (Darling Boy)',
  "If You Don't Know Me by Now ",
  'Been Caught Stealing',
  'Under The Milky Way',
  'End Of The Road',
  'Semi',
  'Start Me Up ',
  'Sabotage ',
  "Annie's Song",
  "I'm Still Standing",
  "(Lover) You Don't Treat Me No Good (Live)",
  'In Between Days',
  'Love...Thy Will Be Done ',
  'Horror Movie ',
  'All Fired Up',
  'U.S. Forces',
  '7 Days',
  'I Try',
  'Kickstart My Heart',
  'Oh, Pretty Woman',
  'Funky Cold Medina',
  'Cold as Ice',
  'Mustang Sally',
  'Someone Like You',
  'Radio Ga Ga ',
  'Desperado (2013 Remaster)',
  'Around the World',
  'Super Trouper',
  'Run to Paradise',
  'Hello, I Love You',
  "U Can't Touch This",
  'Would I Lie To You?',
  "We're Not Gonna Take It",
  'Time After Time',
  'Band On The Run ',
  'Handle With Care',
  "I'm On Fire",
  'Who Do You Think You Are',
  'Bring Me To Life',
  'Walk Like An Egyptian',
  'When a Man Loves a Woman',
  "Don't Look Back in Anger ",
  'The A Team',
  'I Send A Message',
  'Sailing',
  'Never Ever',
  'Smooth Criminal ',
  'Landslide',
  "Reckless (Don't Be So...) ",
  "(Baby I've Got You) On My Mind",
  'Antmusic ',
  'West End Girls ',
  'Money',
  'We Are Family',
  'Where Is The Love?',
  'Everybody Wants To Rule The World',
  'Born To Be Wild',
  'Ray of Light',
  'Our Lips Are Sealed',
  'April Sun in Cuba ',
  'Come On Eileen',
  'California Love ',
  'Jailbreak',
  'Kids In America',
  "You're Still The One",
  'Lightning Crashes',
  "We Didn't Start the Fire",
  'Loser',
  'Fernando',
  'Shout To The Top ',
  'Chasing Cars',
  'Summer Breeze',
  'Chandelier',
  'Patience',
  'Fast Car',
  'Most People I Know',
  'Dr. Feelgood',
  'Crazy',
  'Fastlove, Pt. 1',
  'Legs ',
  'I Knew I Loved You',
  'I Wanna Dance with Somebody (Who Loves Me)',
  'Just the Way You Are',
  'December, 1963 (Oh What a Night!)',
  'I Can See Clearly Now',
  'Valerie',
  'Better Get A Lawyer',
  'Get the Party Started',
  'Can You Feel It',
  'Mmm Mmm Mmm Mmm',
  'The Look',
  "Don't Speak",
  'Road to Nowhere',
  'Together Again',
  'Pride (In The Name Of Love) ',
  'About A Girl ',
  '2000 Miles',
  'You Got It (The Right Stuff)',
  'Forgotten Years ',
  'Jailhouse Rock',
  'By My Side',
  "Don't Stand So Close To Me ",
  'Chase That Feeling',
  'Centerfold',
  'A Horse with No Name',
  'Save Tonight',
  'We Are The World',
  'Stupid Girls',
  'I Want to Know What Love Is ',
  'Royals',
  'Shake It Up',
  'Girls and Boys',
  '7 Seconds (feat. Neneh Cherry)',
  "Don't Bring Me Down",
  "I Don't Want A Lover",
  'No Rain',
  'SexyBack (feat. Timbaland)',
  'This Charming Man ',
  "Tom's Diner",
  'The Flame',
  'Hello',
  'What I Like About You',
  'No Aphrodisiac ',
  'The Whole of the Moon',
  '3AM',
  'Immigrant Song ',
  'I Want It All ',
  'Hold On',
  'Mrs. Robinson',
  'Cherry Cherry',
  'Eye of the Tiger',
  'Tip Of My Tongue',
  'Gonna Make You Sweat (Everybody Dance Now)',
  'The Scientist',
  'Crazy',
  'Abracadabra ',
  'Sultans of Swing',
  'The Boy Is Mine',
  'Let Me Entertain You',
  'The One I Love ',
  'Jolene',
  'All That She Wants ',
  'The Dead Heart ',
  'The Loco',
  'Take It Easy ',
  'Rush You',
  'Everything She Wants',
  "I'm Too Sexy",
  'Last Nite',
  "Don't Go Breaking My Heart",
  'Love In An Elevator',
  'Better',
  'Rain',
  'If You Could Read My Mind',
  'My Girl',
  'Babylon',
  "Greased Lightnin'",
  'You Got Nothing I Want',
  'Two Tribes',
  'All I Wanna Do Is Make Love To You',
  'Use Somebody',
  'I Say A Little Prayer',
  'Living Years',
  'You Get What You Give',
  'Unchain My Heart',
  "I Don't Feel Like Dancin'",
  'Orinoco Flow',
  'Rock Your Body',
  'American Woman',
  'Streets of Your Town',
  'Brown Eyed Girl',
  'Ship of Fools',
  'Firework',
  'Urgent',
  'Hollaback Girl',
  'Pop Muzik ',
  'Total Control',
  'Come Undone',
  'All The Small Things',
  "Don't Get Me Wrong ",
  'Just the Way You Are',
  'Stand by Me',
  'Once in a Lifetime ',
  'Battle Scars',
  'Islands In The Stream',
  "Where's The Love",
  "I'm Not In Love",
  'Send Me An Angel (Re',
  'Blaze Of Glory ',
  'Cars',
  'No Diggity',
  'Glory of Love',
  'Zebra',
  "I Don't Like Mondays",
  'It Must Have Been Love ',
  'You Can Leave Your Hat On',
  'Need You Now',
  'Professional Widow ',
  'The Boxer',
  "I'll Be Missing You (feat. 112)",
  'Dancing in the Street ',
  'Hey Jealousy',
  'Owner of a Lonely Heart',
  'Missing',
  'Androgyny',
  'Ice Ice Baby',
  'Got My Mind Set On You ',
  'Lonely Boy',
  'Run To You',
  'In Da Club',
  'Seven Wonders (Early Version)',
  "Don't Change",
  'Diamonds',
  'Black Hole Sun',
  "Just Can't Get Enough",
  'Beautiful',
  'How to Make Gravy',
  'Dreams',
  'This Is How a Heart Breaks',
  'September',
  'Waterloo',
  'Bust A Move',
  'Celebration',
  'Wish You Well',
  "Boys Don't Cry ",
  'Pretty Fly (For A White Guy)',
  'Heaven Is A Place On Earth',
  "I'll Be There for You (Theme from Friends)",
  'She Sells Sanctuary',
  'If You Had My Love',
  'Addicted To Love',
  'Drops of Jupiter',
  'She Works Hard For The Money',
  'O.P.P. (Re',
  'The Power Of Love',
  'One',
  '100% Pure Love',
  'I Want Your Love',
  "Rollin' (Air Raid Vehicle)",
  'Summer in the City ',
  'I Want You',
  'FourFiveSeconds',
  'Hungry Eyes ',
  'Work It',
  'The Joker',
  'Gloria',
  'Wild, Wild West ',
  'Killing In the Name',
  'Sign Your Name',
  "Girl, You'll Be A Woman Soon",
  'Back on the Chain Gang ',
  'Call On Me ',
  'Scar Tissue',
  'Run to the Hills ',
  'Spinning Around',
  'Just Like Paradise',
  "California Dreamin'",
  'Slave To Love',
  'Sympathy For The Devil',
  '',
  'Underneath the Radar',
  "Big Girls Don't Cry (Personal)",
  'Rebel Yell ',
  'Moonshadow',
  'Refugee',
  'Mr. Brightside',
  'End Of The Line',
  "Knockin' On Heaven's Door",
  'The Look Of Love ',
  'Cosmic Girl',
  'Hey Boy Hey Girl',
  'I Bet You Look Good On The Dancefloor',
  'Only Wanna Be with You',
  'Insane in the Brain',
  'Angel Of Harlem',
  'The Heat Is On ',
  'Like a Stone',
  'All I Want for Christmas Is You',
  'Rock with You ',
  "I'm Free",
  'More Than A Woman',
  'My People',
  'Closer To The Edge',
  'When the Going Gets Tough, The Tough Get Going',
  'Learn to Fly',
  'Upside Down',
  'This Kiss',
  'Baker Street',
  'Tribute',
  'Saltwater',
  "We Can't Be Beaten",
  'Born This Way',
  'Supersonic ',
  'Danger Zone ',
  'Plans',
  'Since U Been Gone',
  'Werewolves of London',
  'Closer',
  'Slice of Heaven',
  'Ignition ',
  'Sweat (A La La La La Long)',
  'Edge of Seventeen',
  "You're Beautiful",
  'A Little Ray Of Sunshine',
  'Together In Electric Dreams ',
  "Let's Groove",
  'As Long as You Love Me',
  'Fight The Power',
  'Is This Love',
  'Hey Joe',
  'Forget You',
  'Take Me Out',
  'S.O.S.',
  'Father Figure ',
  'If You Leave ',
  'Baby Did a Bad, Bad Thing',
  'Raspberry Beret',
  'Viva La Vida',
  "School's Out",
  'Wild Horses',
  'Who Can It Be Now?',
  'American Idiot',
  'Itchycoo Park',
  'Who Knew',
  'Sussudio ',
  'Disarm ',
  'Because the Night',
  'Bed Of Roses',
  'Le Freak',
  'My Island Home',
  "Rapper's Delight ",
  'Are You Gonna Be My Girl',
  'Unbelievable',
  'Kiss You All Over',
  "Don't Leave Me This Way (with Sarah Jane Morris)",
  "What's Up?",
  'Give Me the Night',
  'Locked Out of Heaven',
  'Come Out and Play',
  "Don't Worry Be Happy",
  "Can't Fight The Moonlight",
  "Gangsta's Paradise (feat. L.V.)",
  'High Voltage',
  'Rock DJ',
  'White Wedding ',
  "Ain't No Mountain High Enough",
  'Your Move/Give Peace A Chance Medley',
  'Your Body Is a Wonderland',
  'Solsbury Hill ',
  'Back To Life (However Do You Want Me)',
  'Dizzy',
  'Perfect',
  'Times Like These',
  'Boom! Shake the Room',
  'Paradise By The Dashboard Light',
  'Amazing',
  'Moving on Up',
  'Smalltown Boy',
  "Ain't No Sunshine",
  'The Best Thing',
  'Pony',
  'Rock Lobster',
  'I Believe in a Thing Called Love',
  'Glycerine',
  'Goodbye Yellow Brick Road ',
  'Life in the Fast Lane ',
  'Two Princes',
  'California Girls ',
  'On a Night like This',
  'Copperhead Road',
  'Rock and Roll ',
  'Kiss from a Rose',
  'Hymn to Her ',
  'Riptide',
  'Jet ',
  'You Spin Me Round (Like a Record)',
  'Better Man',
  'What About Me?',
  'Shimmer ',
  "Tonight's the Night (Gonna Be Alright) ",
  'Creep',
  'If I Could Turn Back Time',
  'Black Betty ',
  "Rockin' in the Free World",
  'Just A Girl',
  'Errol ',
  'Father And Son',
  'Fighter',
  'Drop The Pilot',
  'Hound Dog',
  'Listen Like Thieves',
  'Californication',
  'Everytime You Go Away',
  'Sweet Disposition',
  'Get Up, Stand Up',
  'Sunshine Of Your Love',
  'Uptown Girl',
  'Prisoner of Society',
  'Bad Moon Rising',
  'All My Life',
  "Old Time Rock'n'Roll",
  "I Can't Make You Love Me",
  'Tequila Sunrise ',
  'Longview',
  "Can't Fight This Feeling",
  'Stan',
  'Take a Long Line',
  'Four Seasons In One Day',
  'Let Her Go',
  'Panama ',
  'Drive',
  'A Message to You Rudy',
  'Amazing',
  'Foxey Lady',
  'Rock And Roll All Nite',
  'The Rockafeller Skank',
  'If You Love Somebody Set Them Free',
  'Seven Nation Army',
  'Malibu',
  'Burn For You',
  'River Deep ',
  'Bootylicious',
  'Hey, Little Girl',
  'All of Me',
  'The Weight (with Jimmy Barnes)',
  "Rocket Man (I Think It's Going To Be A Long, Long Time)",
  "Steppin' Out",
  'Instant Karma! (We All Shine On)',
  'Not Pretty Enough',
  'Moondance ',
  'Stay With Me',
  'Lady Marmalade',
  'Hard To Handle',
  'The Gambler',
  'La Bamba',
  'Hot In Herre',
  'Bullet With Butterfly Wings',
  "Long Train Runnin'",
  'Walking in Memphis',
  'Try A Little Tenderness',
  'Same Love ',
  'The Ballroom Blitz',
  'Chemical Heart',
  'Buddy Holly',
  "Free Fallin'",
  'I Got You Babe',
  'Private Eyes',
  'Catch My Disease',
  'Runaway Train',
  'Super Freak',
  'Running on Empty',
  'Every Little Thing She Does Is Magic',
  'Doo Wop (That Thing)',
  'The Boys Are Back In Town',
  'Desire',
];

export default Media;
