export const SportsAndGames = [
  'Aaron Donald',
  'Drew Brees',
  'Khalil Mack',
  'Patrick Mahomes',
  'Todd Gurley',
  'Tom Brady',
  'Gronk',
  'Antonio Brown',
  'Aaron Rodgers',
  'Julio Jones',
  'Von Miller',
  'DeAndre Hopkins',
  'J.J. Watt',
  'Michael Thomas',
  'Alvin Kamara',
  'Bobby Wagner',
  'Saquon Barkley',
  'Phillip Rivers',
  'Ezekiel Elliott',
  'Tyreek Hill',
  'Andrew Luck',
  'Travis Kelce',
  'Stephon Gilmore',
  'Odell Beckham Jr.',
  'Luke Kuechly',
  'Russell Wilson',
  'Darius Leonard',
  'Jalen Ramsey',
  'Fletcher Cox',
  'George Kittle',
  'Eddie Jackson',
  'Derwin James',
  'Jared Goff',
  'Adam Thielen',
  'Melvin Gordon',
  'Davante Adams',
  'Chris Jones',
  'Jamal Adams',
  'Keenan Allen',
  'Akiem Hicks',
  'Zach Ertz',
  'Cameron Jordan',
  'Christian McCaffrey',
  'David Bakhtiari',
  'Ben Roethlisberger',
  'DeMarcus Lawrence',
  'Patrick Peterson',
  'JuJu Smith-Schuster',
  'Melvin Ingram',
  'Myles Garrett',
  'Baker Mayfield',
  'Deshaun Watson',
  'Tyron Smith',
  'Mike Evans',
  'Calais Campbell',
  'Xavien Howard',
  'Joey Bosa',
  'Danielle Hunter',
  'A.J. Green',
  'Zack Martin',
  'Larry Fitzgerald',
  'Jaylon Smith',
  'James Conner',
  'Jadeveon Clowney',
  'Amari Cooper',
  'Jason Pierre-Paul',
  'Eric Ebron',
  'Dee Ford',
  'Phillip Lindsay',
  'Matt Ryan',
  'T.Y. Hilton',
  'C.J. Mosley',
  'Jason Kelce',
  'Stefon Diggs',
  'Leighton Vander Esch',
  'Gerald McCoy',
  'Robert Woods',
  'Taylor Lewan',
  'Kirk Cousins',
  'Geno Atkins',
  'Mark Ingram',
  'Trent Williams',
  'Bradley Chubb',
  'Harrison Smith',
  'Jarvis Landry',
  'Frank Clark',
  'Darius Slay',
  'Cam Newton',
  'Cameron Heyward',
  'Devin McCourty',
  'Julian Edelman',
  'Andrew Whitworth',
  'Jurrell Casey',
  'T.J. Watt',
  'Mitchell Schwartz',
  'Kyle Fuller',
  'Carson Wentz',
  'Byron Jones',
  'Tyler Lockett',
  'Derrick Henry',
  'Eric Weddle',
  'Kawhi Leonard',
  'LeBron James',
  'James Harden',
  'Anthony Davis',
  'Stephen Curry',
  'Nikola Jokic',
  'Joel Embiid',
  'Damian Lillard',
  'Paul George',
  'Kyrie Irving',
  'Russell Westbrook',
  'CJ McCollum',
  'Rudy Gobert',
  'Ben Simmons',
  'Luka Doncic',
  'Kemba Walker',
  'Karl-Anthony Towns',
  'Bradley Beal',
  'Donovan Mitchell',
  ' Jimmy Butler',
  'Pascal Siakam',
  'Blake Griffin',
  'Mike Conley',
  "De'Aaron Fox",
  " D'Angelo Russell",
  ' Jamal Murray',
  ' Trae Young',
  ' Tobias Harris',
  ' Devin Booker',
  'Jrue Holiday',
  'Chris Paul',
  'Victor Oladipo',
  'Kristaps Porzingis',
  'Jayson Tatum',
  'Khris Middleton',
  'Al Horford',
  'Draymond Green',
  'Kyle Lowry',
  'Nikola Vucevic',
  'LaMarcus Aldridge',
  'Zion Williamson',
  'Kevin Love',
  'Myles Turner',
  'Aaron Gordon',
  'DeMar DeRozan',
  ' John Collins',
  'Bojan Bogdanovic',
  'Klay Thompson',
  'Lauri Markkanen',
  'Jaylen Brown',
  'Andre Drummond',
  'Clint Capela',
  'Jaren Jackson Jr',
  'Zach LaVine',
  'Brandon Ingram',
  'Malcolm Brogdon',
  'Lou Williams',
  'Buddy Hield',
  'Caris LeVert',
  'Marc Gasol',
  'Joe Ingles',
  'Domantas Sabonis',
  'Shai Gilgeous-Alexander',
  'Gordon Hayward',
  'Deandre Ayton',
  'Eric Bledsoe',
  'Lonzo Ball',
  'Marvin Bagley III',
  'Gary Harris',
  'Dejounte Murray',
  'Montrezl Harrell',
  'JJ Redick',
  'Bogdan Bogdanovic',
  'Steven Adams',
  'Spencer Dinwiddie',
  'Kyle Kuzma',
  'Eric Gordon',
  ' Patrick Beverley',
  'Brook Lopez',
  'Bam Adebayo',
  'PJ Tucker',
  'Jusuf Nurkic',
  'Ricky Rubio',
  'Paul Millsap',
  'Josh Richardson',
  'Marcus Smart',
  'Fred VanVleet',
  'Joe Harris',
  'Otto Porter Jr',
  'Danilo Gallinari',
  'Julius Randle',
  'Ja Morant',
  'Justise Winslow',
  'Jarrett Allen',
  'Derrick Favors',
  'Robert Covington',
  'Mitchell Robinson',
  'Evan Fournier',
  'Derrick White',
  'Steven Nash',
  'Paul Pierce',
  'Allen Iverson',
  'Michael Jordan',
  'Tim Duncan',
  'Magic Johnson',
  'Wilt Chamberlain',
  'Shaq',
  'Kobe Bryant',
  'Larry Bird',
  'Kareem Abdul-Jabbar',
  'Bill Russel',
  'Charles Barkley',
  'Hakeem Olajuwon',
  'Basketball',
  'Soccer',
  'Soccer ball',
  'Baseball',
  'Football',
  'Punt',
  'Kickoff',
  'Squib',
  'Onside kick',
  'Field goal',
  'Extra point',
  'Halftime show',
  'Arena',
  'Stadium',
  'Tennis',
  'Point',
  'Match',
  'Game',
  'Love',
  'Ref',
  'Umpire',
  'First base',
  'Second base',
  'Third base',
  'Home plate',
  'Pitcher’s mound',
  'Strike out',
  'Strike',
  'Ball',
  'Walk',
  'Short stop',
  'Outfield',
  'Pitcher',
  'Catcher',
  'Homerun',
  'Quarterback',
  'Runningback',
  'Center',
  'Guard',
  'Tackle',
  'Defensive line',
  'Offensive line',
  'Tight end',
  'Linebacker',
  'Wide receiver',
  'Coach',
  'Trainer',
  'Three pointer',
  'Swish',
  'Jumpshot',
  'Hail Mary',
  'Fumble',
  'Interception',
  'Steal',
  'Bounce pass',
  'Chest pass',
  'Dunk',
  'Alley-Oop',
  'Timeout',
  'Bench',
  'Glove',
  'Bat',
  'Helmet',
  'Shoulder pads',
  'Atlanta Braves',
  'Miami Marlins',
  'New York Mets',
  'Philadelphia Phillies',
  'Washington Nationals',
  'Chicago Cubs',
  'Cincinnati Reds',
  'Milwaukee Brewers',
  'Pittsburgh Pirates',
  'St. Louis Cardinals',
  'Arizona Diamondbacks',
  'Colorado Rockies',
  'Los Angeles Dodgers',
  'San Diego Padres',
  'San Francisco Giants',
  'American League',
  'Baltimore Orioles',
  'Boston Red Sox',
  'New York Yankees',
  'Tampa Bay Rays',
  'Toronto Blue Jays',
  'Chicago White Sox',
  'Cleveland Indians',
  'Detroit Tigers',
  'Kansas City Royals',
  'Minnesota Twins',
  'Houston Astros',
  'Los Angeles Angels',
  'Oakland Athletics',
  'Seattle Mariners',
  'Texas Rangers',
  'Arizona Cardinals',
  'Atlanta Falcons',
  'Baltimore Ravens',
  'Buffalo Bills',
  'Carolina Panthers',
  'Chicago Bears',
  'Cincinnati Bengals',
  'Cleveland Browns',
  'Dallas Cowboys',
  'Denver Broncos',
  'Detroit Lions',
  'Green Bay Packers',
  'Houston Texans',
  'Indianapolis Colts',
  'Jacksonville Jaguars',
  'Kansas City Chiefs',
  'Los Angeles Chargers',
  'Los Angeles Rams',
  'Miami Dolphins',
  'Minnesota Vikings',
  'New England Patriots',
  'New Orleans Saints',
  'New York Giants',
  'New York Jets',
  'Oakland Raiders',
  'Philadelphia Eagles',
  'Pittsburgh Steelers',
  'San Francisco 49ers',
  'Seattle Seahawks',
  'Tampa Bay Buccaneers',
  'Tennessee Titans',
  'Washington Redskins',
  'Atlanta Hawks ',
  'Boston Celtics ',
  'Brooklyn Nets',
  'Charlotte Bobcats ',
  'Chicago Bulls ',
  'Cleveland Cavaliers ',
  'Dallas Mavericks ',
  'Denver Nuggets ',
  'Detroit Pistons ',
  'Golden State Warriors ',
  'Houston Rockets ',
  'Indiana Pacers ',
  'LA Clippers ',
  'LA Lakers ',
  'Memphis Grizzlies ',
  'Miami Heat ',
  'Milwaukee Bucks ',
  'Minnesota Timberwolves ',
  'New Orleans Hornets ',
  'New York Knicks ',
  'Oklahoma City Thunder ',
  'Orlando Magic ',
  'Philadelphia Sixers ',
  'Phoenix Suns ',
  'Portland Trail Blazers ',
  'Sacramento Kings ',
  'San Antonio Spurs ',
  'Toronto Raptors ',
  'Utah Jazz ',
  'Washington Wizards',
  'Chess',
  'Monopoly',
  'Scrabble',
  'Risk',
  'Settlers of Catan',
  'Clue',
  'Uno',
  'Battleship',
  'Apples to Apples',
  'Yahtzee',
  'Trivial Pursuit',
  'Stratego',
  'Checkers',
  'Sorry!',
  'Pictionary',
  'Connect Four',
  'Go',
  'Backgammon',
  'Axis and Allies',
  'The Game of Life',
  'Candyland',
  'Trouble',
  'Chinese Checkers',
  'Mastermind',
  'Catchphrase',
  'Cranium',
  "Don't Break the Ice",
  'Scattergories',
  'Mahjong ',
  'Dominos',
  'Cards Against Humanity',
  'Guess Who?',
  'Mancala',
  'Taboo',
  'Chutes-And-Ladders',
  'Operation',
  'Balderdash',
];

export default SportsAndGames;
